README.md

Show how images can be built and added to a component version.
Fixes #
```feature user
```

Include refs to more complex makefile examples

---

docs/reference/ocm_add_resource-configuration.md
docs/reference/ocm_add_resources.md
docs/reference/ocm_add_source-configuration.md
docs/reference/ocm_add_sources.md
pkg/contexts/ocm/cpi/accessspecs_simple.go

fix stable output order of option lists

---

pkg/docker/pusher.go

Fixes #158 
```bugfix user
- bugfix #158 
```

fix nil pointer

---

docs/ocm/model.md

Fix resource reference docu
Fixes #
```feature user
```

Fix resource reference docu

---

README.md

Fix the spec link

---

components/demoplugin/Makefile
components/demoplugin/bindings.yaml
components/demoplugin/resources.yaml
components/demoplugin/sources.yaml
components/ocmcli/Makefile
components/ocmcli/resources.yaml

Add multi-platform component builds for all executables.
Fixes #
```feature user
```

provide components for cli and demoplugin

---

docs/formats/artifactdigests/README.md
docs/ocm/model.md
docs/ocm/normalization.md
pkg/signing/normalization.go
pkg/signing/normalization_test.go
pkg/signing/rules.go

Provide normalization docu

---

cmds/ocm/app/prepare.go

fix main help option handling

---

cmds/ocm/pkg/utils/command.go
pkg/contexts/ocm/accessmethods/localblob/cli.go

fix html output in help pages
Fixes #
```feature user
```

fix html output in help pages

---

cmds/ocm/commands/ocmcmds/components/download/cmd.go

fix ocm download cv

---

cmds/ocm/commands/ocmcmds/components/download/cmd.go
pkg/common/accessio/format.go

default dest for download cv

---

cmds/ocm/commands/misccmds/rsakeypair/cmd.go

fix typos in rsa key gen

---

components/helminstaller/Dockerfile
pkg/contexts/ocm/cpi/dummy.go
pkg/contexts/ocm/cpi/support/compversaccess.go
pkg/contexts/ocm/internal/repository.go
pkg/contexts/ocm/repositories/comparch/repository.go
pkg/contexts/ocm/repositories/genericocireg/component.go
pkg/contexts/ocm/utils/resourceref.go
pkg/contexts/ocm/utils/resourceref_test.go
pkg/contexts/ocm/utils/suite_test.go

introduce Dup method to create separately closable handles

---

cmds/ocm/app/app.go
docs/reference/ocm.md
pkg/contexts/ocm/compdesc/componentdescriptor.go
pkg/contexts/ocm/compdesc/helper.go
pkg/contexts/ocm/cpi/support/compversaccess.go
pkg/contexts/ocm/internal/errors.go
pkg/contexts/ocm/repositories/genericocireg/component.go
pkg/contexts/ocm/utils/resourceref.go
pkg/contexts/ocm/utils/resourceref_test.go
pkg/testutils/utils.go

improve dup + more tests

---

cmds/ocm/commands/ocmcmds/common/handlers/elemhdlr/typehandler.go

fix version constraint handling

---

TODO.md
cmds/ocm/app/app.go
cmds/ocm/commands/ocmcmds/common/cmds/signing/cmd.go
cmds/ocm/commands/ocmcmds/common/options/hashoption/option.go
cmds/ocm/commands/ocmcmds/common/options/signoption/option.go
cmds/ocm/commands/ocmcmds/components/cmd.go
cmds/ocm/commands/ocmcmds/components/hash/cmd.go
cmds/ocm/commands/ocmcmds/components/hash/cmd_test.go
cmds/ocm/commands/ocmcmds/components/hash/options.go
cmds/ocm/commands/ocmcmds/components/hash/suite_test.go
cmds/ocm/commands/verbs/describe/cmd.go
cmds/ocm/commands/verbs/hash/cmd.go
cmds/ocm/commands/verbs/verbs.go
cmds/ocm/pkg/output/options.go
cmds/ocm/pkg/output/table.go
docs/reference/ocm.md
docs/reference/ocm_describe.md
docs/reference/ocm_describe_artifacts.md
docs/reference/ocm_describe_plugins.md
docs/reference/ocm_hash.md
docs/reference/ocm_hash_componentversions.md
hack/format.sh
pkg/cobrautils/template.go
pkg/common/walk.go
pkg/contexts/ocm/compdesc/signing.go
pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/bindata.go
pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/bindata.go
pkg/contexts/ocm/signing/handle.go
pkg/contexts/ocm/transfer/transfer.go
pkg/docker/fetcher.go

hash component command

---

cmds/ocm/commands/ocmcmds/components/add/cmd.go

fix non-create mode of add components

---

.github/workflows/release.yaml

Use GA expression for env var in release workflow

---

.github/workflows/release.yaml

Fixing the GH workspace expression

Change GH workspace expression

---

.github/workflows/release.yaml

Change RC version conditional

---

.github/workflows/release.yaml

Fixing the expression for the Release Candidate input in the conditional that sets the version.

Fix expression for RC input

---

docs/releasenotes/v0.2.0.md

Add the release notes for v0.2.0.

Add release notes for v0.2.0

---

pkg/version/release.go

Increase release version to v0.2.0

Bump version to v0.2.0

---

cmds/ocm/app/app.go
cmds/ocm/commands/controllercmds/install/cmd.go
cmds/ocm/commands/verbs/controller/cmd.go
docs/reference/ocm.md
docs/reference/ocm_controller.md
docs/reference/ocm_controller_install.md
pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/bindata.go
pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/bindata.go

update generated files

---

.github/workflows/release.yaml
.goreleaser.yaml

- fix inadvertent removal of certain archs from builds
- add id-token write permission

Release Permissions Fix

---

cmds/ocm/commands/ocmcmds/components/add/cmd.go

fix NPE in cv add

---

.github/workflows/release.yaml

switch release to using token for OCMBot

---

pkg/contexts/credentials/repositories/dockerconfig/provider.go

Switching from propagation of dedicated docker credentials to credential provider
introduced an error when using docker credential helpers.
Fixes #
```feature user
```

fix credential helper handling

---

.github/workflows/release.yaml

use app token for homebrew update

---

README.md
cmds/ocm/commands/ocmcmds/references/add/cmd_test.go
examples/lib/README.md
pkg/contexts/ocm/compdesc/helper.go
pkg/contexts/ocm/compdesc/helper_test.go
pkg/contexts/ocm/compdesc/norm_test.go
pkg/contexts/ocm/compdesc/op.go
pkg/contexts/ocm/compdesc/selectors.go
pkg/contexts/ocm/compdesc/suite_test.go
pkg/generics/cast.go

Offer a public resource selector feature on the internal component descriptor version.
Fixes #
```feature user
```

generalize resource selectors

---

.github/workflows/release.yaml

use OCMBot token for event publishing

---

examples/lib/README.md
examples/lib/config2/example.go
examples/lib/config3/example.go
examples/lib/contexts.md
examples/lib/cred.yaml
examples/lib/cred1/example.go
examples/lib/cred2/example.go
examples/lib/cred3/example.go
examples/lib/example.go
examples/lib/helper/helper.go
pkg/contexts/ocm/interface.go

Update the example programs to work again and provide
more docu about contexts:
- idea
- package organization
- specifications
- handling
Fixes #
```feature user
```

docu for contexts

---

pkg/contexts/ocm/accessmethods/helm/README.md
pkg/contexts/ocm/accessmethods/helm/method.go

Fix helm access method docu

---

Makefile
examples/lib/config1/example.go
examples/lib/config2/example.go
examples/lib/cred2/example.go

adapt examples to new identity packages

---

.github/workflows/lint_and_test.yaml

Fixes #
```feature user
Fix missing go-bindata installation during lint checker testing.
```

bug: fix missing go-bindata installation

---

README.md

add integration test badge to README.md
Fixes #
```feature user
```

add integration test badge

---

examples/lib/example.go
pkg/contexts/ocm/repositories/genericocireg/type.go
pkg/contexts/ocm/repositories/ocireg/type.go

Fixes #378
```feature user
```

fix OCM NewRepositorySpec for type ocireg

---

examples/lib/README.md
examples/lib/transfer.md
examples/lib/transfer1/example.go
examples/lib/transfer1/main.go
pkg/common/accessio/refcloser.go
pkg/contexts/config/configutils/configure.go
pkg/contexts/ocm/interface.go
pkg/contexts/ocm/internal/errors.go
pkg/contexts/ocm/ref.go

add transfer example

---

pkg/finalizer/finalizer.go
pkg/finalizer/finalizer_test.go

fix: length check in if statement for finalizers

---

pkg/contexts/ocm/repositories/comparch/comparch_test.go

The test was wrong and overcomplicated.
Fixes #
```feature user
```

fix component archive tests

---

go.mod
go.sum
pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/bindata.go
pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/jsonscheme.go
pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/bindata.go
pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/jsonscheme.go

Fixes https://github.com/open-component-model/ocm/issues/361
```feature user
```

fix: fix generated content timestamp and mod

---

pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/bindata.go
pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/jsonscheme.go
pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/bindata.go
pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/jsonscheme.go

fix: permanently fix the bindata issue

---

hack/install-requirements.sh
pkg/common/accessio/access.go
pkg/contexts/ocm/transfer/transfer.go
pkg/contexts/ocm/transfer/transferhandler/transferhandler.go
pkg/errors/list.go

Fixes #457
```feature user
```

fix: transfer logic has defer in loop

---

cmds/ocm/commands/ocmcmds/common/inputs/options/standard.go
cmds/ocm/commands/ocmcmds/common/inputs/types/helm/cli.go
cmds/ocm/commands/ocmcmds/common/inputs/types/helm/type.go
docs/reference/ocm_add_resource-configuration.md
docs/reference/ocm_add_resources.md
docs/reference/ocm_add_source-configuration.md
docs/reference/ocm_add_sources.md

add missing helmRepository option for input

---

.github/workflows/pr_run_inttest.yaml

add missing permission for gh action

---

components/ocmcli/Dockerfile

fix missing entrypoint in ocmcli image

---

cmds/helminstaller/app/driver/helm/install.go
cmds/helminstaller/app/execute.go
cmds/ocm/commands/ocmcmds/common/addhdlrs/utils.go
cmds/ocm/commands/ocmcmds/common/cmds/signing/cmd.go
cmds/ocm/commands/toicmds/config/bootstrap/cmd.go
components/helmdemo/Makefile
components/helminstaller/Makefile
go.mod
go.sum
pkg/contexts/ocm/download/handlers/helm/handler.go
pkg/contexts/ocm/repositories/comparch/componentarchive.go
pkg/contexts/ocm/repositories/comparch/repository.go
pkg/contexts/ocm/signing/handle.go
pkg/docker/resolver.go
pkg/toi/drivers/filesystem/driver.go
pkg/toi/install/action.go
pkg/toi/support/app.go

- fix closing component archive repository
- fix toi config bootstrapping
- fix toi resolver handling
- fix to helm installer filesystem driver
- fix helm download handler (does  not return download path)
- improve resource parsing for add commands
- better name for sanitized request field logging
Fixes #471
```feature user
```

some fixes

---

cmds/ocm/app/app.go
docs/reference/ocm.md
docs/reference/ocm_attributes.md
docs/reference/ocm_download_resources.md
docs/reference/ocm_ocm-downloadhandlers.md
pkg/contexts/datacontext/attrs/logforward/attr.go
pkg/contexts/ocm/attrs/mapocirepoattr/attr.go

*improve documentation for attribute mapping
*fix swallowed error if mapping syntax is invalid
Fixes #
```feature user
```

improve documentation for attribute mapping

---

.github/workflows/pr_run_inttest.yaml

fix pr test action not to fail on forked repositories

---

pkg/contexts/ocm/transfer/options.go

fix local transfer option handling

---

hack/generate-docs/cobradoc/space.go
hack/generate-docs/cobradoc/suite_test.go

fix trailing space handling for write sequences

---

README.md

mention and link central web page
```user
```

Add link to central web page at the beginning

---

pkg/env/builder/oci_repo.go
pkg/env/builder/ocm_repo.go

Extend the env builder to not-only generate FS based CTF archives, but handle any spec based repository implementation for OCI and OCM repositories.
added access to external resource, not tested by unit tests.

non-FS based repo instances for env builder

---

cmds/ocm/commands/ocmcmds/components/transfer/cmd.go
cmds/ocm/commands/ocmcmds/components/transfer/cmd_test.go
docs/reference/ocm_add_routingslips.md
docs/reference/ocm_transfer_componentversions.md
pkg/contexts/ocm/compdesc/access/artifacts.go
pkg/contexts/ocm/cpi/accessspec_options.go
pkg/contexts/ocm/cpi/accesstypes.go
pkg/contexts/ocm/cpi/clitypes/clitypes.go
pkg/contexts/ocm/cpi/clitypes/clitypes_options.go
pkg/contexts/ocm/labels/routingslip/spi/entrytype_options.go
pkg/contexts/ocm/labels/routingslip/spi/support.go
pkg/contexts/ocm/transfer/needs.go
pkg/contexts/ocm/transfer/transfer.go
pkg/contexts/ocm/utils/walk.go
pkg/contexts/options/utils.go
pkg/generics/set.go

- option `--bom-file` to request writing a file containing the CV BOM for transfer command
- provide generic implementation for type objects supporitng CLI option provisioning
this will be used for filter types, also, finally used to provide a check functionality for publishing to RBSC inbound repositories. 

First step for RBSC support (write bom file for transfer)

---

pkg/common/accessio/blobaccess/interface.go

During the previous PR #525, the mimetype was moved from being a parameter to being an option. This change was missed to also adjust in the bundling package. 

Dirtree blob access

---

.github/workflows/blackduck_scan.yaml
.github/workflows/blackduck_scan_scheduled.yaml

add detect version

---

pkg/contexts/ocm/download/handlers/blueprint/blueprint_test.go
pkg/contexts/ocm/download/handlers/blueprint/extractor.go
pkg/contexts/ocm/download/handlers/blueprint/handler.go

Added a blueprint mediatype to the blueprint downloader.

add additional blueprint media type to blueprint downloader

---

examples/make/Makefile

chore(examples): fix typo

---

pkg/helm/downloader.go

The helm chart download handler looses credentials for the helm repository.
This is fixed by this PR.

helm repo credential hotfix

---

.github/workflows/release.yaml

fix taken from releases/v0.4.0

fix cosign release

---

pkg/common/accessio/format.go
pkg/common/accessobj/format.go
pkg/contexts/oci/grammar/grammar.go
pkg/contexts/oci/ref.go
pkg/contexts/oci/ref_test.go
pkg/contexts/oci/repositories/artifactset/uniform.go
pkg/contexts/oci/repositories/ctf/uniform.go
pkg/contexts/ocm/grammar/grammar.go
pkg/contexts/ocm/internal/context.go
pkg/contexts/ocm/ref.go
pkg/contexts/ocm/ref_test.go
pkg/contexts/ocm/repositories/comparch/uniform.go
pkg/contexts/ocm/repositories/ctf/ctf_test.go
pkg/contexts/ocm/repositories/ctf/type.go
pkg/contexts/ocm/repositories/ctf/uniform.go
pkg/contexts/ocm/utils.go

This PR fixes a bug, where the resolvers in the ocm context were not updated when calling GetResolvers() which would lead the method to return nil, even though resolvers where configured.
Furthermore, it fixes a bug where the ctf's UniformRepositorySpec tried to map the repository type (CommonTransportFormat) to a file format, which does not work.

Fix update and hint

---

docs/reference/ocm.md
docs/reference/ocm_configfile.md

Add Example for OCM CLI config file

add example

---

pkg/contexts/ocm/accessmethods/ociartifact/method.go
pkg/contexts/ocm/repositories/genericocireg/componentversion.go

remove duplicate code

---

pkg/contexts/credentials/repositories/gardenerconfig/identity/identity.go
pkg/contexts/credentials/repositories/gardenerconfig/repository.go
pkg/contexts/credentials/repositories/gardenerconfig/type.go
pkg/contexts/credentials/repositories/vault/type.go
pkg/contexts/credentials/utils.go
pkg/contexts/oci/repositories/ocireg/type.go
pkg/contexts/ocm/cpi/repocpi/bridge_r.go
pkg/contexts/ocm/repositories/genericocireg/cred_test.go
pkg/contexts/ocm/repositories/genericocireg/type.go
pkg/signing/handlers/rsa-signingservice/client.go
pkg/signing/handlers/rsa-signingservice/credentials.go

Objects may provide information about their expected consumer id.
Therefore an optional additional usage context is passed.
This context is not forwarded correctly by the generic library function, which is fixed by this PR.
Additionally, already the specification objects may now provider consumer id information.
This has also been adapted for the credential repositories requiring credentials.

fix credential provider handling

---

.github/workflows/mend_scan.yaml

Add PR target to action to fix issue with Mend scan.

add PR target

---

cmds/ocm/app/app.go
cmds/ocm/commands/misccmds/rsakeypair/cmd_test.go
docs/reference/ocm.md
docs/reference/ocm_attributes.md
docs/reference/ocm_configfile.md
docs/reference/ocm_logging.md
docs/reference/ocm_sign_componentversions.md
pkg/contexts/ocm/signing/handler_test.go
pkg/signing/handlers/init.go
pkg/signing/handlers/rsa-pss-signingservice/handler.go
pkg/signing/handlers/rsa-pss/handler.go
pkg/signing/handlers/rsa-signingservice/handler.go
pkg/signing/handlers/rsa/certhelper.go
pkg/signing/handlers/rsa/handler.go

Add support for rsa-pss signing:
- direct local signing
- via signing server

signing support for rsa-pss

---

cmds/ocm/commands/ocmcmds/common/resources.go
cmds/ocm/commands/ocmcmds/resources/add/cmd_test.go
cmds/ocm/commands/ocmcmds/resources/add/testdata/helm2.yaml
pkg/contexts/config/configutils/configure.go
pkg/contexts/ocm/utils/configure.go

Some fixes:
- align different configure functions and switch to config context
- fix reference hint check for same resource

Reference Hint Check fixed + alignment of configure function

---

cmds/ocm/commands/ocmcmds/components/check/cmd.go
cmds/ocm/commands/ocmcmds/components/check/cmd_test.go
cmds/ocm/commands/ocmcmds/components/check/options.go
pkg/contexts/ocm/accessmethods/ociartifact/README.md
pkg/contexts/ocm/utils/check/check.go
pkg/contexts/ocm/utils/check/check_test.go
pkg/contexts/ocm/utils/check/options.go
pkg/contexts/ocm/utils/check/suite_test.go
pkg/optionutils/pointer.go

Move basic component check functionality from check command into library.
Package `.../ocm/check` now provides basic chackes bases on some options uses to specify
which checks should be performed.

component version check as lib function

---

.github/workflows/release.yaml

use app token in release

---

pkg/contexts/credentials/builtin/github/identity/identity.go

support for github enterprise urls

---

Dockerfile
cmds/ocm/topics/ocm/labels/topic.go
components/ocmcli/Dockerfile
examples/lib/tour/01-getting-started/README.md

let's add a `user` within Docker

---

cmds/ocm/commands/common/options/keyoption/option.go
cmds/ocm/commands/misccmds/hash/sign/cmd.go
cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go
docs/reference/ocm.md
docs/reference/ocm_add_componentversions.md
docs/reference/ocm_sign_componentversions.md
docs/reference/ocm_sign_hash.md
docs/reference/ocm_verify_componentversions.md

- deprecate the rootverts options and introduce the commonly used ca-certs options
- get rid of the artificial constraint for the relation enforced by the input/access mode when composing a component version.
now an appropriate relation is defaulted, but not enforced anymore (access -> external, input -> local).

align ca-cert opts + remove relation constraints for inputs

---

pkg/common/accessobj/cachedblob_test.go
pkg/contexts/datacontext/attrs/tmpcache/attr.go
pkg/contexts/ocm/accessmethods/github/method_test.go
pkg/contexts/ocm/accessmethods/s3/method_test.go

There can occur an issue, when trying to create tempFiles:
```
<*fmt.wrapError | 0xc0008f2240>:
unable to read access: unable to create temporary file: mkdir C:\FOO~1\TEMP\user: lstat /C:: CreateFile C:/FOO~1/TEMP/user/VFS-1551776656/C:: The filename, directory name, or volume label syntax is incorrect.
msg: "unable to create temporary file: mkdir C:\\FOO~1\\TEMP\\user: lstat /C:: CreateFile C:/FOO~1/TEMP/user/VFS-1551776656/C:: The filename, directory name, or volume label syntax is incorrect."
err: <*fs.PathError | 0xc0008f47e0>{
Op: "mkdir",
Path: "C:\\FOO~1\\TEMP\\user",
Err: <*fs.PathError | 0xc0008f47b0>{
Op: "lstat",
Path: "/C:",
Err: <*fs.PathError | 0xc0008f4780>{
Op: "CreateFile",
Path: "C:/FOO~1/TEMP/user/VFS-1551776656/C:",
Err: <syscall.Errno>0x7b,
```
Please include a …

fix issue with create tempfile on MS Windows

---

cmds/ocm/app/app.go
cmds/ocm/commands/ocmcmds/common/handlers/comphdlr/sort.go
cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/options.go
cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/sort.go
cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go
cmds/ocm/commands/ocmcmds/components/cmd.go
cmds/ocm/commands/ocmcmds/components/list/cmd.go
cmds/ocm/commands/ocmcmds/components/list/cmd_test.go
cmds/ocm/commands/ocmcmds/components/list/suite_test.go
cmds/ocm/commands/verbs/list/cmd.go
cmds/ocm/commands/verbs/verbs.go
cmds/ocm/pkg/output/tableoutput.go
docs/reference/ocm.md
docs/reference/ocm_add_sources.md
docs/reference/ocm_list.md
docs/reference/ocm_list_componentversions.md
pkg/common/types.go
pkg/contexts/ocm/compdesc/componentdescriptor.go
pkg/contexts/ocm/session.go
pkg/semverutils/sort.go

The `ocm get cv` command can be used to detect and filter existing versions for a component, if the given specification omits
a version name. But because the component versions are completely read from the repository to provide additional information fr the output list, it is quite slow.
To just get a list of available versions a new `ocm list cv` is provided, which can be used just to detect available versions.
Also the yaml and json flavors just prvide the found versions and no further information. Therefore, the found versions must not be read from the repository and the list can be determined much faster.
Like for the `get`command a version is only read if a given specification involves a version name to check, whether the version exists.
The version constraint options from the …

fast version list command

---

Dockerfile
cmds/ocm/pkg/output/tableoutput.go
components/helminstaller/Dockerfile
pkg/version/version.go
version.go

incorporate VERSION file if built without make

---

pkg/env/builder/ocm_version_test.go
pkg/toi/install/credentials_test.go

Fixes https://github.com/open-component-model/ocm-project/issues/43

fix: remove all personal information from tests

---

cmds/ocm/commands/ocmcmds/common/handlers/comphdlr/typehandler.go
cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go

normalize order of used component lister results

---

cmds/ocm/commands/controllercmds/common/applyer.go
cmds/ocm/commands/controllercmds/common/fetcher.go
cmds/ocm/commands/controllercmds/common/manifests.go
cmds/ocm/commands/controllercmds/install/install_cert_manager.go
cmds/ocm/commands/controllercmds/install/resource_manager.go
cmds/ocm/commands/controllercmds/uninstall/cmd.go
cmds/ocm/commands/controllercmds/uninstall/cmd_test.go
cmds/ocm/commands/controllercmds/uninstall/issuer/registry_certificate.yaml
cmds/ocm/commands/controllercmds/uninstall/resource_manager.go
cmds/ocm/commands/controllercmds/uninstall/suite_test.go
cmds/ocm/commands/controllercmds/uninstall/testdata/install.yaml
cmds/ocm/commands/controllercmds/uninstall/uninstall_cert_manager.go
cmds/ocm/commands/verbs/controller/cmd.go
cmds/ocm/commands/verbs/verbs.go

Closes https://github.com/open-component-model/ocm-project/issues/37

feat: add uninstall command to the controller

---

.github/workflows/flake_vendorhash.yaml

body out var can't span across multiple lines :-(

fix updateVendorHash

---

.github/workflows/flake_vendorhash.yaml

let's see if the create-PR action is able to sign commits

sign flake.nix updates

---

.github/workflows/lint_and_test.yaml

This is needed to make the tests for https://github.com/open-component-model/ocm/pull/810 succeed!

adjust github action definition

---

.github/workflows/lint_and_test.yaml

Adjust action

---

.github/workflows/flake_vendorhash.yaml

- create the commit only if there is a difference
- create commit on the branch, which change go.mod/go.sum
- act on pull requests

enhance the auto update of the flake vendor hash

---

.github/workflows/release.yaml

fix deprecated option in goreleaser

fix goreleaser

---

api/ocm/extensions/pubsub/providers/ocireg/provider.go

ignore status error for reading pubsub config

---

api/ocm/elements/artifactblob/npmblob/access_test.go
api/ocm/ocmutils/walk.go
api/ocm/tools/signing/digest_test.go
api/ocm/tools/signing/store_test.go
api/utils/blobaccess/npm/access_test.go
cmds/ocm/commands/ocmcmds/common/inputs/types/npm/input_test.go
cmds/ocm/commands/ocmcmds/common/inputs/types/ocm/input_test.go
cmds/ocm/commands/ocmcmds/components/sign/cmd_test.go
cmds/ocm/commands/ocmcmds/components/verify/cmd_test.go
cmds/ocm/commands/ocmcmds/verified/get/cmd_test.go

Function does not make too much sense without it.

Add cv parameter to walking step function

---

.github/workflows/components.yaml
.github/workflows/lint_and_test.yaml
api/ocm/add_test.go

fix: runner caching code that it uses

---

.github/workflows/components.yaml
.github/workflows/lint_and_test.yaml

small change to test github actions

---

api/ocm/tools/signing/handle.go

extend signing list component descriptors

---

cmds/ocm/commands/controllercmds/install/cmd.go
docs/reference/ocm_controller_install.md

fix: default component download link

---

cmds/ocm/commands/ocmcmds/common/options/keepglobaloption/option.go
cmds/ocm/commands/ocmcmds/common/options/omitaccesstypeoption/option.go
cmds/ocm/commands/ocmcmds/common/options/overwriteoption/option.go
cmds/ocm/commands/ocmcmds/common/options/rscbyvalueoption/option.go
cmds/ocm/commands/ocmcmds/common/options/skipdigestoption/option.go
cmds/ocm/commands/ocmcmds/common/options/srcbyvalueoption/option.go
cmds/ocm/commands/ocmcmds/common/options/stoponexistingoption/option.go
docs/reference/ocm_add_componentversions.md
docs/reference/ocm_transfer_commontransportarchive.md
docs/reference/ocm_transfer_componentarchive.md
docs/reference/ocm_transfer_componentversions.md

I guess it should be: `If the option ...` and not 'It the option'

Documentation: `If the option ...`

---

api/credentials/internal/identity.go
api/utils/listformat/listhelp.go
api/utils/registrations/info.go
cmds/ocm/commands/ocmcmds/common/options/downloaderoption/option.go
cmds/ocm/commands/ocmcmds/common/options/uploaderoption/option.go
cmds/ocm/commands/ocmcmds/resources/get/cmd.go
cmds/ocm/commands/ocmcmds/sources/get/cmd.go
cmds/ocm/common/output/treeoutput.go
docs/reference/ocm_add_componentversions.md
docs/reference/ocm_download_resources.md
docs/reference/ocm_ocm-downloadhandlers.md
docs/reference/ocm_ocm-uploadhandlers.md
docs/reference/ocm_transfer_commontransportarchive.md
docs/reference/ocm_transfer_componentversions.md

- apply sorting to output of handler descriptions for up- and downloaders
- improve tree output element title handling

some fixes and alignments

---

api/ocm/tools/signing/digest.go
hack/Makefile

fix + doc for VerifyResourceDigest

---

.github/workflows/publish.yaml

[chore]: Install wingetcreate

---

.github/workflows/publish.yaml
api/oci/extensions/repositories/ocireg/namespace.go
api/oci/extensions/repositories/ocireg/utils.go

Fixes: https://github.com/open-component-model/ocm/issues/949

fix: docker registry returning internal server error on blobs not found

---

.github/workflows/release.yaml

adjust github token for ocm push

---

.github/workflows/release.yaml

Revert workflow adjustments

---

.github/workflows/release.yaml

fix workflow file

---

.github/workflows/flake_vendorhash.yaml

The current action ends up in an endless loop, since it updates the PR which triggered it.
With v7 of `peter-evans/create-pull-request` we're now able to easily create PRs with multiple files and a signed commit!

fix: GHA - .github/workflows/flake_vendorhash.yaml

---

api/ocm/extensions/pubsub/providers/ocireg/provider.go

Related to https://github.com/open-component-model/ocm/issues/872 and https://github.com/open-component-model/ocm/pull/904

fix: ignore ORA error instead of containerd error

---

.github/workflows/release-branch.yaml

fix: setting up the github name and email

---

.github/workflows/release-branch.yaml

fix: use a permission token for pushing a new tag

---

.github/workflows/release-branch.yaml

fix: using the bot token to check out the repository

---

api/oci/extensions/repositories/ocireg/namespace.go
api/oci/extensions/repositories/ocireg/repository.go

Closes https://github.com/open-component-model/ocm-project/issues/273

fix: wrap the TLS config into a retryer client (#968)

---

examples/lib/tour/01-getting-started/README.md

chore: update readme

---

.github/workflows/stale.yaml

Adds a stale bot configuration
fix [#285](https://github.com/open-component-model/ocm-project/issues/285)
fyi @morri-son

chore(ci): add stale bot for issues

---

.github/workflows/release.yaml

fix: remove ocm release key if present

---

README.md

Adjust README with rotated GPG key

---

examples/lib/tour/01-getting-started/README.md

this will be (hopefully) the last bump before we create an automatically generated PR after a release which bumps this generation or we decide to stop updating the tour with the latest release

chore: change guide for 0.18.0

---

.github/workflows/flake_vendorhash.yaml

makes sure they disappear from the release notes since they are just bumps in main that people dont really care about

chore: add correct labels for flake nix job

---

examples/lib/tour/07-resource-management/README.md
examples/lib/tour/07-resource-management/example.go

Why should every release require us to re-generate the samples?

chore(example): let's limit the listed versions

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/user_story.md
.github/config/labeler.yml
.github/config/release.yml
.github/dependabot.yml
.github/workflows/flake_vendorhash.yaml
.github/workflows/pull-request.yaml

chore(backport): adjust labels to new configuration

---

.github/workflows/publish-latest.yaml

https://github.com/open-component-model/ocm/issues/947 
fixes: https://github.com/open-component-model/ocm-project/issues/291

chore(platforms): publish for: linux/amd64 and linux/arm64

---

RELEASE_PROCESS.md

Fix typos and remove resolved TODOs.

chore: docs/release process

---

.github/workflows/blackduck_scan.yaml

correct certain settings and change name of yaml

chore: finalize blackduck scan

---

.github/workflows/blackduck_scan.yaml
.github/workflows/codeql.yml

add scheduled trigger to full scan and add recommendations from security team to CodeQL

chore: add scheduled trigger to full scan

---

.github/workflows/codeql.yml

add actions to checked languages

chore: Update codeql.yml

---

api/credentials/extensions/repositories/vault/auth.go
api/tech/maven/access.go
api/utils/utils.go

let's use go 1.24 features
follow up on https://github.com/open-component-model/ocm/pull/1304

chore(refactor): replace utils.MapKeys with slices.Collect(maps.Keys(m))

---

.github/workflows/blackduck_scan.yaml

correct workflow before merging PR

correct workflow

---

.github/workflows/blackduck_scan.yaml

correct worklfow

---

.github/workflows/blackduck_scan.yaml

remove PR comment

---

.github/workflows/blackduck_scan.yaml

add upload

---

api/oci/extensions/repositories/ocireg/repository.go

Fixes https://github.com/open-component-model/ocm/issues/1353

fix: always initialize the system certificate store for the oras client

---

api/oci/extensions/repositories/ocireg/repository.go

backport of https://github.com/open-component-model/ocm/pull/1378
https://github.com/open-component-model/ocm/issues/1366

fix: set the refresh token to password always

---

.github/workflows/trigger-blackduck-scan.yaml

Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
update Black Duck scan workflow reference to specifc commit

chore: update Black Duck scan workflow reference to specific commit

---

go.mod

chore: update to go v1.24.2
