open-component-model/ocm

pkg/contexts/oci/grammar/grammar.go, pkg/contexts/oci/ref_test.go
The legacy notation for dockerhub based references uses a name restriction for the repository
which can be used to differentiate between dockerhub references and flat image names stored in some
other OCI registry.
Fixes #
=> differentiate between docker repository name and hostname

cmds/ocm/commands/common/options/closureoption/option.go, cmds/ocm/pkg/tree/tree.go, pkg/common/walk.go, pkg/contexts/clictx/builder.go, pkg/contexts/datacontext/context.go, pkg/contexts/oci/repositories/docker/type.go, pkg/contexts/ocm/cpi/accessspecs_converted.go, pkg/contexts/ocm/cpi/accessspecs_simple.go, pkg/contexts/ocm/repositories/genericocireg/component.go, pkg/contexts/ocm/signing/options.go, pkg/contexts/ocm/transfer/transferhandler/standard/options.go, pkg/env/builder/builder.go, pkg/env/builder/oci_artefact.go, pkg/signing/handlers/rsa/format.go, pkg/utils/utils.go
There are several implementation to handle a variadic parameters to default an optional argument.
Using generics these different implementations can be harmonized by central oe.
This assures always the same behaviour of the currently different implementations.
Fixes #
Unfortunately with go generics it is not possible to differentiate between value types and nil-able
types. 
If we choose `comparable` as type parameters which would include pointer types, `interfaces` cannot be passed.
If we choose `any` we cannot compare and would need `reflect.DeepEqual` to select the first non-zero element.
Therefore this generalization is not possible without using reflection and various …
=> generalize a common handling for optional arguments

cmds/ocm/commands/ocmcmds/common/resources.go, pkg/contexts/ocm/cpi/dummy.go, pkg/contexts/ocm/cpi/support/compversaccess.go, pkg/contexts/ocm/cpi/support/container.go, pkg/contexts/ocm/internal/blobhandler.go, pkg/contexts/ocm/internal/blobhandler_test.go, pkg/contexts/ocm/internal/repository.go, pkg/contexts/ocm/repositories/genericocireg/repo_test.go
A blob handler is responsible for storing local blobs in an alternate way.
For example, in a OCI registry backend for OCM repositories, local blobs describing an OCI artifact are exploded and stored as regular OCI artifacts, again. The access spec in the CD is adapted accordingly.
Therefore a blob handler gets a storage context describing the technical target repository and the blob (including its mime type). It then decides whether it will handle the blob or not. If yes, it has to return an appropriate access spec usable to access the content. 
Similar is the registration, handlers are registered for implementation repositories types and mime types.
Both is optional. Even if a registration constraint matches, the handler may reject the handling of …
=> extend blobhandler context/registration with artifact type

cmds/ocm/commands/ocicmds/artefacts/download/cmd.go, pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/bindata.go, pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/bindata.go
If the destination option for `ocm download artefact` is not given and only one artefact is downloaded
an invalid directory name is used.
Fixes #
```feature user
```
=> fix omitted dest option for artifact download

Makefile, components/demoplugin/Makefile, components/helminstaller/Makefile, components/ocmcli/Makefile, hack/cross-build.sh
=> fix makefiles

pkg/contexts/credentials/builtin/github/ghcr.go, pkg/contexts/credentials/builtin/init.go, pkg/contexts/credentials/init.go
If a `GITHUB_TOKEN` is found in the environment appropriate credentials are set for the actual `GITHUB_HOST`.
Fixes #
```feature user
```
=> builtin support for GitHub token

cmds/ocm/commands/ocmcmds/components/hash/cmd.go, cmds/ocm/commands/ocmcmds/components/hash/options.go, docs/reference/ocm_hash_componentversions.md, pkg/contexts/oci/repositories/ocireg/type.go, pkg/contexts/ocm/repositories/genericocireg/uniform.go
It extends the hash command to write normalized component descriptors into files.
Fixes #
```feature user
```
=> option to write normalized cd into file(s)

.github/workflows/lint_and_test.yaml
We need to add a `workflow_call` to the lint/test workflow so that it can be used from the release workflow, which failed here due to this: https://github.com/open-component-model/ocm/actions/runs/4005104187
=> Add `workflow_call` to lint workflow

.github/workflows/release.yaml
Error: https://github.com/open-component-model/ocm/actions/runs/4005777395 
Add permissions for the lint/test job to use it in the release workflow.
=> Add permissions to release workflow

.github/workflows/release.yaml
Renaming release notes directory to `releasenotes` for consistency. Hopefully this is the last thing to debug before creating an RC 🤞
=> Rename release notes directory

.github/workflows/release.yaml, .goreleaser.yaml
- Fixing the following Goreleaser errors: https://github.com/open-component-model/ocm/actions/runs/4007881021/jobs/6881323108 by ensuring that the Go versions in `go-cache` step matches the one in `go.mod`.
- Replacing the deprecated `archives` config for goreleaser from the warning, see: https://goreleaser.com/deprecations/#archivesreplacements
- Adding a `needs` to the release job to ensure that there is a successful run of lint-and-tester beforehand.
=> Fixes for release workflow

.github/workflows/release.yaml
Using `actions/setup-go@v3` to set the Go version correctly in the release worfklow to match the Go version in `go.mod`.
=> Set Go version in release workflow

.github/workflows/release.yaml
This PR triggers an event to update the release version for the `ocm` CLI in the ocm website.
Addresses https://github.com/open-component-model/ocm/issues/238 for the `ocm` CLI
=> Add event to update version on website

.github/workflows/release.yaml, .goreleaser.yaml
This PR updates the release workflow to publish a homebrew forumla for the OCM CLI to the 'open-component-model/homebrew-tap' repository.
Fixes #239
Should also address #227 
Signed-off-by: Piaras Hoban <phoban01@gmail.com>
=> Add Homebrew to Release Process

cmds/ocm/commands/ocmcmds/common/options/uploaderoption/uploader_test.go, cmds/ocm/commands/ocmcmds/common/resources.go, cmds/ocm/commands/ocmcmds/components/transfer/cmd.go, cmds/ocm/commands/ocmcmds/resources/download/cmd.go, hack/format.sh, pkg/contexts/credentials/config/config_test.go, pkg/contexts/ocm/compdesc/versions/ocm.gardener.cloud/v3alpha1/jsonscheme/bindata.go, pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/bindata.go, pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/jsonscheme.go, pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/bindata.go, pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/jsonscheme.go, pkg/contexts/ocm/utils/localize/config_test.go, pkg/signing/normalization_test.go
Add `gofmt` to the `make format` command. The PR also includes the changes introduced by `gofmt`.
Fixes #29
=> add gofmt to make format and run

cmds/ocm/commands/ocicmds/artifacts/transfer/cmd.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/refs/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/srcs/elements.go, cmds/ocm/commands/ocmcmds/common/cmds/signing/cmd.go, cmds/ocm/commands/ocmcmds/common/handlers/elemhdlr/typehandler.go, cmds/ocm/commands/ocmcmds/components/transfer/cmd.go, cmds/ocm/commands/toicmds/components/bootstrap/cmd.go, pkg/cobrautils/flagsets/provider.go, pkg/contexts/credentials/internal/credentialsspec.go, pkg/contexts/credentials/repositories/aliases/type.go, pkg/contexts/credentials/repositories/dockerconfig/type.go, pkg/contexts/credentials/repositories/gardenerconfig/type.go, pkg/contexts/credentials/repositories/memory/config/type.go, pkg/contexts/credentials/repositories/memory/type.go, pkg/contexts/oci/cpi/base.go, pkg/contexts/oci/cpi/flavor_artifact.go, pkg/contexts/oci/cpi/support/base.go, pkg/contexts/oci/cpi/support/flavor_artifact.go, pkg/contexts/ocm/accessmethods/localblob/method.go, pkg/contexts/ocm/accessmethods/localfsblob/method.go, pkg/contexts/ocm/blobhandler/generic/ocirepo/registration.go, pkg/contexts/ocm/blobhandler/oci/ocirepo/blobhandler.go, pkg/contexts/ocm/blobhandler/ocm/comparch/blobhandler.go, pkg/contexts/ocm/repositories/genericocireg/state.go
#22 - This PR adds type assertion checks where it feel sensible in order to avoid `nil` pointer referencing that causes runtime panics. 
There are still a lot of type assertions occurring in the code, but adding checks for many of these either didn't make sense in the context, or would require code refactoring beyond the scope of the ticket.
Fixes #22
=> check type assertions where it makes sense to avoid runtime panics

Makefile, components/demoplugin/Makefile, components/helminstaller/Dockerfile, components/ocmcli/Makefile, hack/cross-build.sh, hack/install.sh
#226 - Not all `date` commands are made equal. To resolve the issue we can specify the exact format of the date we want rather than use the `--rfc-3339` flag. There is a minor, but inconsequential difference in the output.
See below output:
GNU Date:
```
❯ gdate --rfc-3339=seconds | sed 's/ /T/'
2023-02-16T11:50:12+00:00
```
With explicit formatting:
```
❯ date -u +%FT%TZ
2023-02-16T11:51:20Z
```
Alternatively, we can remove the `Z` with:
```
❯ date -u +%FT%T%z
2023-02-16T11:52:38+0000
```
If the above is preferred I am happy to change it.
Fixes #226
=> update date command in Makefile to work crossplatform

cmds/ocm/commands/ocmcmds/components/cmd.go, cmds/ocm/commands/ocmcmds/ctf/cmd.go, pkg/contexts/ocm/compdesc/versions/v2/signing.go, pkg/runtime/unstructured.go
- error message for non-exsisting access method type for CV composition.
- fix CV normalization field for componentReferences.
- fix missing command verb combinations.
Fixes #
```feature user
```
=> some fixes

pkg/testutils/signing_test.go, pkg/testutils/string.go, pkg/testutils/suite_test.go
Extend the context based string comparison matcher for gomega by the possibility to specify substitution
variables
This will later be used for the signature tests to provide a single source of truth for the expected hashes
in command outputs and manifests.
Fixes #
```feature user
```
=> gomega string comparison with substitution

.github/workflows/release.yaml, .goreleaser.yaml
This change updates the release process to produce build artifacts inline with standard practices.
We update the goreleaser config with the following changes:
- ensure the `version.gitVersion`, `version.gitCommit`, `version.buildDate` package variables are set when building the ocm binary
- change the template format for archives to `{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- add SBOM
- add checksum signing
The following is the output produced:
**Please note**
Sigstore will require authentication to sign the release, the link is generated and printed to the log output. So please monitor the log for this link when executing release following this change.
Fixes #286 
@mandelsoft please kindly confirm that …
=> Update release process

.github/release-drafter.yml, docs/releasenotes/v0.3.0.md, pkg/version/release.go
This PR adds the release notes for `v0.3.0`.
It also appends `v` since the release-drafter cuts this for some reason.
=> Add release notes for `v0.3.0`

cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go, cmds/ocm/commands/ocmcmds/common/inputs/types/docker/spec.go, cmds/ocm/commands/ocmcmds/common/inputs/types/dockermulti/spec.go, cmds/ocm/commands/ocmcmds/common/inputs/types/helm/cli.go, cmds/ocm/commands/ocmcmds/common/inputs/types/helm/spec.go, cmds/ocm/commands/ocmcmds/common/inputs/types/helm/type.go, cmds/ocm/commands/ocmcmds/common/inputs/types/ociimage/spec.go, cmds/ocm/commands/ocmcmds/resources/add/cmd_test.go, cmds/ocm/commands/ocmcmds/resources/add/testdata/helm.yaml, pkg/contexts/ocm/accessmethods/ociartifact/utils.go
Support `repository` field for input type `helm`` to provide an explicit  repository
hint for helm charts.
Allow arbitrary resource versions for local resources during CV composition.
Fixes #
```feature user
```
=> hint for helm input + arbitrary resource version

pkg/contexts/ocm/utils/localize/README.md, pkg/contexts/ocm/utils/localize/format.go, pkg/contexts/ocm/utils/localize/localize.go, pkg/contexts/ocm/utils/localize/localize_test.go, pkg/contexts/ocm/utils/localize/subst.go, pkg/contexts/ocm/utils/localize/target_test.go, pkg/contexts/ocm/utils/localize/utils_test.go
This PR deals with localization on a single data object.
The change introduces some basic functions around a type `ValueMappings` , which just describes a set of substitution rules, which can be applied to a single data object (`SubstituteMappings`) . With `LocalizeMappings` a set of (pure non-filename based) localization rules can be mapped to such value mappings combined with config mappings and then applied to a single byte array,
Fixes #300
```feature user
```
=> simple data localization

.golangci.yaml, go.mod, go.sum
I created a fork here https://github.com/open-component-model/cobra
Applied the in question fix and set up a midnight everyday auto update syncer that will auto approve and merge PRs.
Right now, the action fails if there are no changes. This can be ignored by setting `ignore_fail: true`. But sadly, that will ignore every failure not just the no change failure.
Fixes #53
```feature user
Replace cobra personal fork with project based fork with auto updating action.
```
=> chore(dep): replace personal fork with auto-updating project fork

cmds/ocm/commands/common/options/formatoption/option.go, cmds/ocm/commands/ocmcmds/componentarchive/transfer/cmd.go, cmds/ocm/commands/ocmcmds/components/transfer/cmd.go, cmds/ocm/commands/ocmcmds/components/transfer/cmd_test.go, cmds/ocm/commands/ocmcmds/ctf/transfer/cmd.go, pkg/contexts/ocm/utils.go
The `--type` option is ignored if a CTF is target of a transfer operation and the CTF has to be created.
Fixes #
```feature user
```
=> fix CTF type usage for creation

pkg/contexts/oci/grammar/grammar.go, pkg/contexts/ocm/cpi/ref.go, pkg/contexts/ocm/internal/uniform.go, pkg/contexts/ocm/ref.go, pkg/contexts/ocm/ref_test.go, pkg/contexts/ocm/repositories/genericocireg/uniform.go
localhost or other potentially non DNS like host name parts in OCM ref expressions are not handled
correctly, even if the repository type prefix is given.
To solve the general ref parsing there is already a type UniformRepositorySpec, which holds various
parts of a reference and which is then mapped by heuristics to dedicated repository specs.
The problem here is that these heuristics cannot be unique if the intended type is not known.
Now we add type specific handlers, which can normalize the uniform spec according to the constraints
of the dedicated type.
Additionally, the OCIRegistry handler for mapping of URSs has been extended to handle the Info field, if host is not set,
Fixes #
**Special notes for your …
=> improve ocm ref parsing

go.mod, go.sum, pkg/contexts/credentials/cpi/interface.go, pkg/contexts/credentials/interface.go, pkg/contexts/credentials/internal/consumers.go, pkg/contexts/credentials/internal/context.go, pkg/contexts/credentials/ref_test.go, pkg/contexts/credentials/repositories/dockerconfig/credentials.go, pkg/contexts/credentials/repositories/dockerconfig/provider.go, pkg/contexts/credentials/repositories/dockerconfig/repo_test.go, pkg/contexts/credentials/repositories/dockerconfig/repository.go, pkg/contexts/datacontext/context.go, pkg/finalizer/object.go, pkg/finalizer/object_test.go, pkg/generics/map.go
Instead of propagating single credentials for single consumers, it is possible now
to add complete CosumerProviders handling consumer requests.
The explicit consumer registry has been replaced by an internal standard consumer provider
and the Docker Config repository has been migrated to provide such a consumer provider.
Consumer providers and entries now have an optional provider id, which can be used
to clean up all setting from one provider. This can be used to refresh or delete providers,
again.
Additionally, the contexts now feature a unique Id for debugging and logging.
They also offer a possibility now to check, whether a context has been garbage collected
as expected when getting rid of a context.
The Credentials Context now has a test for …
=> Support Consumer Providers + Migrate DockerConfig

pkg/contexts/credentials/builtin/github/github.go, pkg/contexts/credentials/doc.go, pkg/contexts/ocm/accessmethods/github/method.go, pkg/contexts/ocm/download/handlers/helm/download.go, pkg/contexts/ocm/download/handlers/helm/handler.go, pkg/contexts/ocm/download/registry.go
This PR separates the OCM specific part of the OCM helm downloader from the generic OCI specific part
to make it reusable for other clients.
Additionally it add doc for the credential handling with credential context.
Fixes #
```feature user
```
=> support for helm artifact downloading from OCI artifacts for landscaper

pkg/contexts/ocm/accessmethods/ociartifact/method.go, pkg/contexts/ocm/digester/digesters/artifact/digester.go
Signing a resource of access type ociArtifact the digest must be determined. This fails if there is a permission problem.
The actually used Digest method (as part of the BlobAccess interface) does not provide an error return value,
therefore the signing error does not tell the reason for the failed signing.
The BlobAccess interface is very basic and used all over the code, therefore it is hard to change.
But the actual problem arises from accessing the access method. Here a better method with error return
is added to provide the fail reason, if the digest determination fails.  
Fixes #
```feature user
```
=> provide digest error for OCI artifacts

cmds/ocm/commands/ocmcmds/references/add/cmd_test.go, pkg/contexts/ocm/compdesc/helper.go, pkg/contexts/ocm/cpi/dummy.go, pkg/contexts/ocm/cpi/interface.go, pkg/contexts/ocm/cpi/support/compversaccess.go, pkg/contexts/ocm/cpi/support/container.go, pkg/contexts/ocm/cpi/support/references.go, pkg/contexts/ocm/cpi/support/resources.go, pkg/contexts/ocm/interface.go, pkg/contexts/ocm/internal/context.go, pkg/contexts/ocm/internal/repository.go, pkg/contexts/ocm/internal/repotypes.go
The selection feature on the level of the component descriptor
has been used to support similar functionality on at a ComponentVersionAccess.
Thereby the method signatures have been aligned. Unfortunately the 
signature on CD level for the reference selection had to be changed here.
To support this, the support implementation for ComponentVersionAccess implementations
has been lifted to a true wrapper around an implementation object, which provides
all methods, which can be implemented in a generic manner on top of the implementation object.
Fixes #
```feature user
```
=> provide selectors on access level of ocm context

pkg/contexts/credentials/identity/hostpath/id_test.go, pkg/contexts/credentials/repositories/dockerconfig/provider.go, pkg/contexts/credentials/repositories/gardenerconfig/repository.go, pkg/contexts/ocm/accessmethods/localblob/method.go, pkg/contexts/ocm/cpi/interface.go, pkg/contexts/ocm/digester/digesters/blob/digester.go, pkg/contexts/ocm/registration/downloader.go, pkg/contexts/ocm/registration/uploader.go
The internal packages primary purpose is to prevent cyclic dependencies between its respective context package and its cpi (context programming interface) package. 
Fixes #
The pkg/contexts/registration package is also adjusted. But as this is not exactly an extension point, one could argue whether this should in fact use the internal package. 
```feature user
```
=> clean up usage of internal package

cmds/ocm/commands/ocmcmds/componentarchive/create/cmd.go, pkg/common/accessobj/format-directory.go
if the target file already exists an arrors is reported, but the file is deleted.
Fixes #314
```feature user
```
=> fix ca creation for existing file

cmds/ocm/commands/cachecmds/clean/cmd.go, cmds/ocm/commands/cachecmds/info/cmd.go, docs/reference/ocm_clean_cache.md, pkg/common/accessio/cache.go, pkg/errors/list.go, pkg/utils/time.go
The filesystem cache for blobs now supports an API for a cache cleanup.
It supports a dry-run mode and a time based mode.
It is accessible using an option interface `CacheCleanup`.
This way it can programatically be used from a library without the command line interface.,
Fixes #
```feature user
```
=> time based cache cleanup

cmds/ocm/commands/ocmcmds/common/handlers/comphdlr/closure.go, cmds/ocm/commands/ocmcmds/common/handlers/elemhdlr/typehandler.go, cmds/ocm/commands/ocmcmds/resources/get/deep_test.go
While creating the history in traversing a component version hierarchy, the entries in the list
are overwritten for deeper nestings.
Fixes #
```feature user
```
=> fix history creation in tree output of cvs

examples/lib/transfer.md, examples/lib/transfer1/example.go
fix the finalization of the nested loop in the transfer example.
add explanation for the transfort closure handling.
Fixes #
```feature user
```
=> fix transfer example

pkg/contexts/oci/ref_test.go, pkg/contexts/oci/repositories/ocireg/namespace.go, pkg/contexts/oci/repositories/ocireg/repository.go, pkg/contexts/ocm/repositories/genericocireg/repo_test.go, pkg/contexts/ocm/repositories/genericocireg/spec_test.go, pkg/contexts/ocm/repositories/ocireg/type.go, pkg/testutils/utils.go
Creating an oci based OCM repository spec with NewRepositorySpec creates corrupted
specification objects when passing a scheme based URL with a port part.
This PR now parses the scheme part separately and created an appropropriate wrapped
OCI repository spec for the OCM repository spec. 
Fixes #
```feature user
```
=> handle scheme based URL in OCM repo spec

cmds/ocm/app/app.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/utils.go, cmds/ocm/commands/ocmcmds/common/inputs/types/directory/inputtype_test.go, cmds/ocm/commands/ocmcmds/common/resources_test.go, pkg/contexts/credentials/internal/context.go, pkg/contexts/credentials/internal/cred_test.go, pkg/contexts/credentials/internal/credentialsspec.go, pkg/contexts/credentials/repositories/directcreds/type.go, pkg/contexts/ocm/accessmethods/localfsblob/method.go, pkg/contexts/ocm/accessmethods/localfsblob/method_test.go, pkg/contexts/ocm/repositories/comparch/accessmethod_test.go, pkg/contexts/ocm/repositories/genericocireg/type.go, pkg/runtime/encoding.go, pkg/runtime/encoding/encoding.go, pkg/runtime/remove.go, pkg/runtime/scheme.go, pkg/runtime/scheme_test.go, pkg/runtime/unstructured.go, pkg/runtime/validation/suite_test.go, pkg/runtime/validation/validate.go, pkg/runtime/validation/validate_test.go
Add a `StrictMode`for the library to improve the object deserialization 
to validate the decoded objects against the initial data to check for
unexpected fields.
Add support to parse a set of object parts separately.
Fix all the the places where an object unmarshalling is delegated to 
unmarshal enriched object types using embedded fields. 
Fixes #
```feature user
```
=> generic object validation

go.mod, go.sum, pkg/contexts/ocm/repositories/virtual/access.go, pkg/contexts/ocm/repositories/virtual/accessmethod_localblob.go, pkg/contexts/ocm/repositories/virtual/component.go, pkg/contexts/ocm/repositories/virtual/componentversion.go, pkg/contexts/ocm/repositories/virtual/example/doc.go, pkg/contexts/ocm/repositories/virtual/example/example.go, pkg/contexts/ocm/repositories/virtual/index.go, pkg/contexts/ocm/repositories/virtual/repo_test.go, pkg/contexts/ocm/repositories/virtual/repository.go, pkg/contexts/ocm/repositories/virtual/spec.go, pkg/contexts/ocm/repositories/virtual/suite_test.go, pkg/contexts/ocm/repositories/virtual/testdata/blobs/blob1, pkg/contexts/ocm/repositories/virtual/testdata/blobs/blob2, pkg/contexts/ocm/repositories/virtual/testdata/descriptors/cd1.yaml, pkg/contexts/ocm/repositories/virtual/testdata/descriptors/cd2.yaml, pkg/contexts/ocm/session.go, pkg/contexts/ocm/utils/configure.go
This PR provides an OCM repository implementation based on two simple implementation interfaces, These interfaces 
can be implemented to provide virtual repositories based on some mapping of existing data structures.
It is intended to map OCM information provided in some context to be presented as complete OCM repository.
This will be used to map the inline OCM component descriptors optionally provided by a *Landscaper Installation*
to an OCM repository view. This enables to use those virtual environments exactly like a regular OCM repository context,
which avoids special cases for the regular installation processing coding.
An example implementation of these interfaces is based on some files in a virtual filesystem. It is used for the test cases, …
=> Provide default implementation to support implementations of simple virtual/simulated OCM repositories,

pkg/contexts/credentials/repositories/dockerconfig/provider.go
In the docker config file the auth map may contain host:port pairs as keys. This is not correctly handled
in the credentials repository implementation for dockerconfig.
Fixes #
```feature user
```
=> fix evaluation of docker config file

pkg/contexts/ocm/compdesc/meta/v1/labels.go, pkg/contexts/ocm/compdesc/meta/v1/labels_test.go, pkg/contexts/ocm/compdesc/meta/v1/suite_test.go
The `Set` for the label set cannot modify existing labels correctly. This is fixed.
Additionally, some useful access methods for labels and tests are added.
Fixes #
```feature user
```
=> fix and extend label access functions

cmds/ocm/commands/ocmcmds/common/inputs/options/standard.go, cmds/ocm/commands/ocmcmds/common/inputs/types/utf8/cli.go, cmds/ocm/commands/ocmcmds/common/inputs/types/utf8/inputtype_test.go, cmds/ocm/commands/ocmcmds/common/inputs/types/utf8/spec.go, cmds/ocm/commands/ocmcmds/common/inputs/types/utf8/type.go, docs/reference/ocm_add_resource-configuration.md, docs/reference/ocm_add_resources.md, docs/reference/ocm_add_source-configuration.md, docs/reference/ocm_add_sources.md
The input type `utf8` now supports additional modes:
- (field `text`: utf8 text)
- field `json`: output JSON, input inline json/yaml or json/yaml string
- field `formattedJson`: output formatted JSON, input inline json/yaml or json/yaml string
- field `yaml`: output YAML, input inline json/yaml or json/yaml string
Fixes #
```feature user
```
=> extend utf8 input type to accept and generate YAML/JSON content

cmds/ocm/commands/ocmcmds/cli/download/cmd.go, cmds/ocm/commands/ocmcmds/cli/download/cmd_test.go, cmds/ocm/commands/ocmcmds/common/inputs/types/utf8/inputtype_test.go, cmds/ocm/commands/ocmcmds/common/options/versionconstraintsoption/option.go, cmds/ocm/commands/ocmcmds/resources/download/action.go, cmds/ocm/commands/ocmcmds/resources/download/options.go, cmds/ocm/pkg/utils/fileutils.go, docs/pluginreference/plugin.md, docs/pluginreference/plugin_accessmethod_validate.md, docs/pluginreference/plugin_action_execute.md, docs/pluginreference/plugin_descriptor.md, docs/pluginreference/plugin_download.md, docs/reference/ocm_credential-handling.md, docs/reference/ocm_download_resources.md, docs/reference/ocm_get_credentials.md, docs/reference/ocm_ocm-downloadhandlers.md, pkg/contexts/credentials/cpi/const.go, pkg/contexts/oci/identity/identity.go, pkg/contexts/oci/repositories/ocireg/repository.go, pkg/contexts/ocm/compdesc/logging_test.go, pkg/contexts/ocm/compdesc/meta/v1/labels_test.go, pkg/contexts/ocm/compdesc/norm_test.go, pkg/helm/identity/identity.go
Adds the possibility to verify TLS certificates of oci registries with CA certificates passed as part of the credentials. This is useful to e.g. run tests with locally running oci registries whose certificates might be dynamically generated.
Fixes #
```feature user
```
=> CA certificate of oci registry as part of credentials

pkg/contexts/ocm/compdesc/componentdescriptor.go, pkg/contexts/ocm/interface.go, pkg/contexts/ocm/internal/repository.go, pkg/contexts/ocm/transfer/debug.go, pkg/contexts/ocm/transfer/needs.go, pkg/contexts/ocm/transfer/transfer.go, pkg/contexts/ocm/transfer/transferhandler/standard/handler_test.go
To decide, which resources have to be transported the digest is not sufficient to handle re-transports
of exactly the same content with different transport modes (value vs reference).
This Pr checks, whether access methods would have to be changed according to the
the actual state in the target repository and the chosen transport mode. This then
controls the transport flow of a dedicated component version.
Additionally it should also handle the preserving of existing artifacts for overwrite transports.
There are several new tests now for those scenarios.
Fixes #513
```feature user
```
=> consider transport modes for transport flow decisions

pkg/contexts/oci/repositories/ocireg/repository.go
Remove the TLS version constraint for OCI registry access quay.io uses a much older one (303)
Fixes #532
=> relaxed TLS version for OCI access

cmds/ocm/commands/ocmcmds/common/inputs/types/docker/spec.go, cmds/ocm/commands/ocmcmds/common/inputs/types/docker/type.go, cmds/ocm/commands/ocmcmds/common/inputs/types/dockermulti/spec.go, cmds/ocm/commands/ocmcmds/common/inputs/types/dockermulti/type.go, docs/names/labels.md, docs/reference/ocm_add_resource-configuration.md, docs/reference/ocm_add_resources.md, docs/reference/ocm_add_routingslips.md, docs/reference/ocm_add_source-configuration.md, docs/reference/ocm_add_sources.md, pkg/contexts/oci/annotations/annotations.go, pkg/contexts/oci/artdesc/artifact.go, pkg/contexts/oci/artdesc/index.go, pkg/contexts/oci/artdesc/manifest.go, pkg/contexts/oci/repositories/artifactset/utils_synthesis.go
=> support for image back links

.github/workflows/components.yaml, .github/workflows/lint_and_test.yaml
change actions from fixed go version to go-version-file
=> adopt to go-version-file

cmds/ocm/commands/ocmcmds/common/inputs/types/docker/spec.go, cmds/ocm/commands/ocmcmds/componentarchive/create/cmd_test.go, cmds/ocm/commands/ocmcmds/components/get/cmd_test.go, pkg/contexts/ocm/compdesc/compdesc_test.go, pkg/contexts/ocm/compdesc/norm_test.go, pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/componentdescriptor.go, pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/validation_test.go, pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/version.go
So far, if one wanted to Encode/Decode a Component Descriptor to v3alpha1, this had to be specified with the corresponding constant v3alpha1.GroupVersion while for v2, this had to be specified with the corresponding constant v2.SchemaVersion.
This behaviour is quite confusing and should therefore be adjusted.
=> adjust v3alpha1 schema version

.golangci.yaml, cmds/ocm/commands/controllercmds/install/cmd.go, cmds/ocm/commands/controllercmds/install/cmd_test.go, cmds/ocm/commands/controllercmds/install/install_cert_manager.go, cmds/ocm/commands/controllercmds/install/issuer/registry_certificate.yaml
Add a pre-flight check to see if all conditions are met that are required for the controller to work before installing it.
Closes https://github.com/open-component-model/ocm-controller/issues/285
=> feat: add pre-flight check for installing ocm-controller

cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/components.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/interface.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/refs/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/srcs/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/utils.go, cmds/ocm/commands/ocmcmds/components/add/cmd_test.go, cmds/ocm/commands/ocmcmds/components/add/testdata/component-dup-ref.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/component-dup-res.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/component-dup-src.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/components-dup.yaml, cmds/ocm/commands/ocmcmds/references/add/cmd_test.go, cmds/ocm/commands/ocmcmds/references/add/testdata/references-dup.yaml, go.mod, pkg/contexts/ocm/compdesc/meta/v1/types.go, pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/validation.go, pkg/contexts/ocm/compdesc/versions/v2/validation.go
The add commands now check for duplicate ids for resources, sources and references in specs and report
appropriate problems with the location in the source yaml files.
The same check is done for adding multiple components to avoid overwrite of components from the same action.
The CD validation now reports the identity of the validated component version, if the validation fails.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your …
=> duplicate detection for add commands

cmds/ocm/commands/ocmcmds/components/transfer/cmd.go, cmds/ocm/commands/ocmcmds/components/transfer/disableupload_test.go, docs/reference/ocm_add_resource-configuration.md, docs/reference/ocm_add_resources.md, docs/reference/ocm_add_source-configuration.md, docs/reference/ocm_add_sources.md, docs/reference/ocm_controller.md, docs/reference/ocm_controller_install.md, docs/reference/ocm_logging.md, docs/reference/ocm_transfer_componentversions.md, pkg/contexts/ocm/internal/context.go
This PR introduces the option `--disable-uploads`  for the command `ocm transfer components`.
If combined with `--copy-resources` it can be used to provide a completely self-contained component version artifact on the target side of the transport. All resources (or sources with `--copy-sources`) will be stored as local blobs
on the target side.
If the target is an OCI registry, the complete content of a component version is stored in a single OCI artifact
This transport mode is intended to be used for the RBSC upload tools intended to be used to uniformly publish SAP OCM components via the repository based shipment channel.
Attention: This is a quick-win implementation of this feature just disabling the uploaders in the context.
A better implementation would provide this feature via …
=> simple support for disabling uploaders

pkg/helm/downloader.go
This PR fixes a bug in the helm downloader where the found credentials where not actually used.
This led to problems for landscaper stakeholders when trying to use apply installations using helm charts.
=> Fix Helm Downloader Credential Handling

.goreleaser.yaml
Cosign >v2.0.0 requires the `--yes`  flag to be explicitly set in the goreleaser manifest.
ref: https://goreleaser.com/customization/sign/#signing-with-cosign
=> Update Goreleaser cosign handling

pkg/helm/downloader.go, pkg/helm/identity/identity.go, pkg/helm/identity/identity_test.go, pkg/helm/identity/suite_test.go
The helm download requires two kinds of credentials, helm credentials for helm repos and
OCI credentials for OCI registries. This PR fixes this and provides appropriate tests.
=> Fix OCI repository credential handling for downloading Helm charts

cmds/ocm/commands/ocmcmds/common/inputs/cpi/helper.go, cmds/ocm/commands/ocmcmds/common/inputs/types/file/support.go
So far, the behavior was to deducted from the media type (if the media type contained the suffix gzip, the file was compressed). This is quite unintuitive especially since a user might quite frequently provide an already compressed file (such as a helm chart archive).
=> change the default compressing behavior to false for file input type

cmds/ocm/commands/ocmcmds/components/sign/cmd_test.go, pkg/common/accessobj/accessstate.go, pkg/common/accessobj/check.go, pkg/contexts/oci/repositories/ctf/uniform.go, pkg/contexts/ocm/interface.go, pkg/contexts/ocm/internal/errors.go, pkg/contexts/ocm/repositories/comparch/uniform.go, pkg/contexts/ocm/resolver.go
Parsing a command line repository spec is improved to better distinguish CA and CTF variants.
A CTF is only enforced if the target has
- either the required descriptor file
- or if has no files
This gives spec handlers later in the list the chance to detect their type.
May be, a rework would be useful, where handlers distinguish between a default and a direct match.
So far, the first match exists the handler processing. With a default match, all handlers could be executed to look
for a direct match. A default match would only be used if no direct match is found.
Second problem is the compound resolver. If a component archive is used as resolver, if reports a not found error
for the component, instead of the requested component version. The error condition is fixed accordingly.
- Related …
=> fix ref detection for ca/ctf

README.md, flake.lock, flake.nix
This is a flake enablement for the repository of ocm. nix enabled environments can easily import ocm with
```
nix run github:open-component-model/ocm
nix run github:open-component-model/ocm#demo
nix run github:open-component-model/ocm#helminstaller
...
```
nix can hermetically build the package automatically on various architectures. 
With the flakes includes the the ocm repo, we can contribute our project into the nixos.org package library.
=> Make ocm flake.nix ready

cmds/ocm/app/app.go, docs/reference/ocm.md, pkg/contexts/credentials/repositories/dockerconfig/default.go, pkg/contexts/ocm/utils/configure.go, pkg/contexts/ocm/utils/defaultconfigregistry/configure.go, pkg/listformat/listhelp.go
Introduce a handler registry to handle default configuration.
It is used to provide a default configuration for a context, if no
`.ocmconfig` is found or given.
So far, itwas hard-coded to incorporate the docker config.
With NPM we get a second source for default config.
Therefore, it is useful to replace the hard-wired solution by a registry
based one. This also reverses the dependency direction. OCM now does not have
a direct dependency to the docker implementation, anymore. Instead the docker
implementation registers itself for the default configuration handling.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
=> default config handlers

cmds/ocm/commands/ocmcmds/components/check/cmd.go, cmds/ocm/commands/ocmcmds/components/check/options.go, pkg/contexts/ocm/internal/resolver.go, pkg/contexts/ocm/session.go
The repository cache was not able to deal with repository specs that contained fields that cannot be marshalled (since the marshalled repository spec is used as key). 
This issue was already resolved in the session implementation that essentially implemented its own repository cache. To reduce code duplication and avoid such errors in the future, the session now uses the repository cache implementation. 
=> Fix repository cache

pkg/contexts/ocm/accessmethods/wget/cli.go, pkg/contexts/ocm/accessmethods/wget/method.go
This PR complements the documentation for the http access method, since the responsible developer forgot to add it [here](https://github.com/open-component-model/ocm/pull/630).
=> add documentation for wget access

cmds/ocm/commands/ocmcmds/components/add/cmd.go, docs/reference/ocm_add_componentversions.md
Minor change to the ocm command documentation.
=> change wording

.github/workflows/lint_and_test.yaml, .gitignore, Makefile, docs/reference/ocm_controller.md, docs/reference/ocm_controller_uninstall.md, docs/reference/ocm_credential-handling.md, docs/reference/ocm_get_credentials.md, examples/lib/tour/doc.go, go.mod, go.sum, hack/Makefile, pkg/contexts/credentials/cpi/interface.go, pkg/contexts/credentials/internal/consumers.go, pkg/contexts/credentials/internal/context.go, pkg/contexts/credentials/internal/identity.go, pkg/contexts/credentials/internal/logging.go, pkg/contexts/credentials/repositories/dockerconfig/provider.go, pkg/contexts/credentials/repositories/npm/provider.go, pkg/contexts/credentials/repositories/vault/a_usage.go, pkg/contexts/credentials/repositories/vault/identity/identity.go, pkg/contexts/credentials/repositories/vault/options.go, pkg/contexts/credentials/repositories/vault/provider.go, pkg/contexts/credentials/repositories/vault/repo_int_test.go, pkg/contexts/credentials/repositories/vault/repo_test.go, pkg/contexts/credentials/repositories/vault/repository.go, pkg/contexts/credentials/repositories/vault/type.go
Implement integration tests with vault.
It also fixes a bug where getting the credentials for a consumer provider lead to a deadlock or potentially an infinite recursion since we attempt to retrieve credentials to access the credential provider from the credential provider itself.
We might want to discuss the naming of the make targets. Thus, should `make test` run all tests including integration? Or should `make test` only run unit tests and `make test-all` (this is how I currently introduced it here) include integration tests?
Also, is it important that we have a make target which can run the integration tests exclusively (without including the unit tests)? This would require adding build tags to all tests.  
> Remove if not …
=> Vault tests

pkg/contexts/ocm/cpi/repocpi/bridge_c.go, pkg/contexts/ocm/repositories/composition/repository_test.go
When adding a CV to a component, the CD validation is done deep in the call chain when updating the CV on the persistence layer. This typically happens during closing a CV which provides strange error messages.
To provider a better error message the validation is now done directly in the add call.
=> early CD validation for AddVersion

cmds/ocm/commands/controllercmds/common/log.go, cmds/ocm/commands/controllercmds/common/manifests.go, cmds/ocm/commands/controllercmds/install/cmd.go, cmds/ocm/commands/controllercmds/install/cmd_test.go, cmds/ocm/commands/controllercmds/install/install_cert_manager.go, cmds/ocm/commands/controllercmds/uninstall/cmd_test.go
https://github.com/open-component-model/ocm-project/issues/67
=> fix: only have yaml out put on stdout if dryrun is enabled

Makefile, cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go, cmds/ocm/commands/ocmcmds/common/inputs/types/maven/spec.go, cmds/ocm/commands/ocmcmds/components/add/cmd.go, cmds/ocm/coretests/maven/cmd_test.go, cmds/ocm/coretests/maven/suite_test.go, cmds/ocm/coretests/maven/testdata/components.yaml, cmds/ocm/coretests/maven/testdata/components2.yaml, go.mod, go.sum, pkg/blobaccess/maven/options.go, pkg/contexts/ocm/accessmethods/maven/method.go, pkg/contexts/ocm/accessmethods/maven/method_test.go, pkg/contexts/ocm/blobhandler/handlers/generic/maven/blobhandler.go, pkg/contexts/ocm/elements/artifactblob/mavenblob/access_test.go, pkg/contexts/ocm/elements/artifactblob/mavenblob/options.go, pkg/contexts/ocm/elements/artifactblob/mavenblob/resource.go, pkg/maven/access.go, pkg/maven/coordinates.go, pkg/maven/maventest/const.go
This PR fixes upload issues and introduces the option to upload blob during composition. So, you can now do the following: 
`ocm add cv --file /tmp/ctf components.yaml --uploader ocm/mavenArtifact=file://localhost/mavenrepo` 
with the components.yaml looking something like this:
```yaml
components:
- name: ocm.software/demo/test
version: 1.0.0
provider:
name: ocm.software
resources:
- name: mavenartifact
type: mavenArtifact
input:
type: maven
path: /maven/testdata/.m2/repository
groupId: "com.sap.cloud.sdk"
artifactId: "sdk-modules-bom"
version: "5.7.0"
```
For the uploader to trigger here (and therefore, for the uploader option to be effective with this command), it is crucial that you try to add a local blob (and thus, have an `input:` instead of an `access:` in your constructor file).
=> fix maven issues

cmds/ocm/commands/ocmcmds/common/inputs/types/maven/input_test.go, cmds/ocm/commands/ocmcmds/common/inputs/types/maven/testdata/resources1.yaml, cmds/ocm/coretests/maven/cmd_test.go, cmds/ocm/coretests/maven/testdata/components.yaml, cmds/ocm/coretests/maven/testdata/components2.yaml, go.mod, go.sum, pkg/contexts/ocm/blobhandler/handlers/generic/maven/blobhandler.go, pkg/contexts/ocm/blobhandler/handlers/generic/maven/blobhandler_test.go, pkg/contexts/ocm/blobhandler/handlers/generic/maven/registration.go, pkg/contexts/ocm/elements/artifactaccess/mavenaccess/resource.go, pkg/contexts/ocm/elements/artifactblob/mavenblob/resource.go, pkg/contexts/ocm/resourcetypes/const.go, pkg/maven/access.go, pkg/maven/coordinates.go
The resource type `mavenArtifact` was renamed to `mavenPackage` to avoid misunderstandings. Maven defines the term maven artifact as any file stored in maven (addressable by a GAVCE) while a mavenPackage describes all files stored under a particular GAV.
=> fix maven uploader and rename mavenArtifact to mavenPackage

.github/workflows/flake_vendorhash.yaml
see how PRs would look like:
https://github.com/hilmarf/ocm/pull/7
=> finally at least be able to sign commits

.github/workflows/flake_vendorhash.yaml, flake.lock
Whenever module dependencies change, we need to update the vendor hash in `flake.nix`.
This PR updates now the GHA to do this automatically and produces also signed & verified commits :-)
=> auto update `flake.nix` vendor hash incl. singed commit

cmds/ocm/commands/ocmcmds/plugins/describe/describe.go, cmds/ocm/commands/ocmcmds/plugins/get/cmd.go, cmds/subcmdplugin/cmds/cmd_test.go, cmds/subcmdplugin/cmds/demo/cmd.go, docs/command-plugins.md, pkg/contexts/ocm/plugin/cache/plugin.go, pkg/contexts/ocm/plugin/cache/plugindir.go, pkg/contexts/ocm/plugin/cache/updater.go, pkg/contexts/ocm/plugin/ppi/cmds/command/cmd.go
Rework the plugin client interface to grant access to the source info without exposing the complete internal cache information.
=> rework source info access for plugin clients

cmds/subcmdplugin/cmds/cmd_test.go, cmds/subcmdplugin/cmds/demo/cmd.go, pkg/contexts/ocm/plugin/cache/exec.go, pkg/contexts/ocm/plugin/plugin.go
- If the plugin is called via `go run` (like in the tests), this command adds an implicit error status line, which
must be handled in the plugin adapter to find the correct error json.
- The plugin might provide error output. This error output must be separated from the formal error status
- As long as we don't have a formal way to get to the stderr stream from the context, the error output is added
to the error message
=> fix plugin error propagation

pkg/contexts/ocm/plugin/plugin.go
During execution of CLI command extensions the command name ist used twice as argument for calling the plugin.
=> fix duplicate command argument for plugin command execution

cmds/demoplugin/valuesets/check_test.go, pkg/cobrautils/logopts/options_test.go, pkg/contexts/ocm/accessmethods/plugin/cmd_test.go, pkg/contexts/ocm/grammar/grammar.go, pkg/contexts/ocm/grammar/grammar_test.go, pkg/contexts/ocm/grammar/suite_test.go, pkg/filelock/lock_test.go
Users created components with complex semver versions (e.g. 0.2.3+2024.T06b). This lead to problems, for example when calling `ocm get references ./registry//github.com/acme.org/helloworld:0.2.3+2024.T06b`.
This PR extends the version regex used by ocm to also support such complex semver version numbers.
=> Extend version regexp to support semver

pkg/docker/errors/errors.go, pkg/docker/pusher.go
the used containerd lib extracts a potential error from the response body of an OCI rest call, but
the error object does not report this content with its Error method.
The error object has been copied into this library and fixed accordingly.
=> forward error message from OCI registry

pkg/signing/handlers/rsa/handler.go
This fixes a bug that caused verification of rsassa-pss signatures to fail.
=> Exchange Algorithm constant in polymorphic handler method

README.md
Make OCM more convenient to consume for users of Arch Linux.
Note: there are different ways (and tools) to consume packages from AUR (hence just a reference to documentation rather than a concrete shellscript-snippet). I think it is safe to assume Arch Linux users will be able to consume packages from AUR without such help ;-)
=> Add AUR as installation option for OCM-CLI

.github/workflows/check_diff_action.yaml
=> feat: add check for diffs after go mod tidy and generate

api/utils/cobrautils/links.go, cmds/ocm/commands/ocicmds/cmd.go, cmds/ocm/commands/ocmcmds/cmd.go, cmds/ocm/commands/toicmds/config/bootstrap/cmd.go, cmds/ocm/common/utils/command.go, cmds/ocm/topics/toi/bootstrapping/topic.go, docs/reference/ocm_bootstrap_configuration.md, docs/reference/ocm_bootstrap_configuration_toi-bootstrapping.md, docs/reference/ocm_bootstrap_package.md, docs/reference/ocm_bootstrap_package_toi-bootstrapping.md, docs/reference/ocm_configfile.md, docs/reference/ocm_describe_package_toi-bootstrapping.md, docs/reference/ocm_oci.md, docs/reference/ocm_ocm.md, docs/reference/ocm_toi-bootstrapping.md, hack/generate-docs/cobradoc/md_docs.go
Links ins CLI documentation are not working if they relate to invisible commands, because for those commands
no document is created.
This is fixed by using a new cobra annotation to declare command path mappings (`commandPath`).
It is evaluated by the CLI doc generator to adapt generated links and command path output.
Besides this new feature some wrongly defined explicit command refs are fixed.
=> fix cli docu generation

api/ocm/cpi/dummy.go, api/ocm/cpi/interface.go, api/ocm/cpi/modopts.go, api/ocm/cpi/repocpi/interface.go, api/ocm/cpi/repocpi/view_cv.go, api/ocm/cpi/utils.go, api/ocm/extensions/repositories/composition/type.go, api/ocm/extensions/repositories/virtual/type.go, api/ocm/interface.go, api/ocm/internal/repository.go, api/ocm/internal/resolver.go, api/ocm/resolver.go, api/ocm/resolver_test.go, api/ocm/types/interface.go, cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/suite_test.go, cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go, cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler_test.go, cmds/ocm/commands/ocmcmds/common/options/lookupoption/option.go
CLI command `ocm list componentversions` dumps if only a component is specified together with a resolver (either as part of the config or as option).
This PR fixes this dump.
The resolvers are only able to resolve component versions. Therefore, after the fix the provided list does not show any version for the given component. The expected behaviour would surely be to get the list of versions resolvable by the given resolvers.
Not all resolvers are able to provide repositories offering a version list method. Therefore an optional interface is introduced for
resolvers, which provide potential repositories for a given component. This interface offers the possibility to return repositories or abstract component providers which can be used to get versions or version lists.
This is then checked …
=> introduce optional repository interface for resolvers

cmds/ocm/commands/toicmds/cmd.go, cmds/ocm/common/utils/command.go, docs/reference/ocm_toi.md
=> more path mappings

api/credentials/builtin/oci/identity/identity.go, docs/reference/ocm_credential-handling.md, docs/reference/ocm_get_credentials.md, hack/Makefile
This PR fixes typos.
Additionally, it fixes the Make target `make install-requirements` because of missing `bin` directory.
=> fix: typo + missing bin directory

.github/workflows/release.yaml, sonar-project.properties
The regular setup-go has already a [caching mechanism integrated](https://github.com/actions/setup-go?tab=readme-ov-file#caching-dependency-files-and-build-outputs)
Fixes #847
=> disable manual/secondary caching

api/ocm/extensions/accessmethods/npm/method_test.go, api/ocm/extensions/accessmethods/options/standard.go, cmds/ocm/commands/ocmcmds/common/inputs/options/standard.go, cmds/ocm/commands/ocmcmds/common/inputs/types/npm/cli.go, cmds/ocm/commands/ocmcmds/common/inputs/types/npm/input_test.go, cmds/ocm/commands/ocmcmds/common/inputs/types/npm/spec.go, cmds/ocm/commands/ocmcmds/common/inputs/types/npm/suite_test.go, cmds/ocm/commands/ocmcmds/common/inputs/types/npm/type.go, docs/pluginreference/plugin_accessmethod_compose.md, docs/pluginreference/plugin_descriptor.md, docs/pluginreference/plugin_valueset_compose.md
Adds the `npm` input type.
Closes https://github.com/open-component-model/ocm-project/issues/199
=> feat: add npm input type

api/ocm/extensions/repositories/genericocireg/annotation_test.go, api/ocm/extensions/repositories/genericocireg/componentversion.go, api/ocm/resolver_test.go, cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler_test.go, cmds/ocm/commands/ocmcmds/common/inputs/types/npm/input_test.go
@maximilianbraun a very quick and dirty and in no way production ready experiment to annotate the oci layers with component information. 
Since currently, the abstraction in code is intended to add all kinds of blobs to all kinds of storage backends, a clean solution would require several adjustments. A quick solution could introduce further options containing such metadata. Then the different storage implementation could choose whether to use or ignore those metadata. Furthermore, we might also want more metadata (e.g. to distinct sources from resources and to also annotate the descriptor layer itself).
=> annotate oci layers with component information

.github/workflows/buildcomponents.yaml, .github/workflows/check_diff_action.yaml, .github/workflows/components.yaml, .github/workflows/lint_and_test.yaml, .github/workflows/push_ocm.yaml, .github/workflows/release-drafter.yaml, .github/workflows/release.yaml
Speed up the executed github actions.
There is no need to cache manually in most cases.
And there is normally no need to fetch the complete git history.
=> Chore: setup-go@v4 does caching automatically

api/ocm/extensions/repositories/genericocireg/type.go, api/ocm/plugin/cache/updater.go, cmds/ocm/commands/ocmcmds/components/get/cmd_test.go, cmds/ocm/common/output/treeoutput.go, cmds/ocm/common/tree/convert.go, cmds/ocm/common/tree/tree_test.go, go.mod, go.sum
A binary just written cannot be executed while the file is still open for write (even on Unix).
Therefore, we have to close the file for the plugin executable, before it can be executed to extract
the plugin descriptor.
=> fix busy text file during plugin installation

api/tech/maven/access.go, api/utils/blobaccess/maven/access_test.go
Some repos do automatically redirect from 
https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.9 to https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.9/ (<<-- see the slash at the end)
But Sonatype Nexus Repository (OSS 3.71.0-06) don't!!!
And their returned index-of page, which should list the repository content can't be fetched, when not sending a proper 'User-Agent' header. And the listing contains absolute links instead of relative ones.
=> fix: some weird maven repositories do return bad index-of listings

api/ocm/compdesc/meta/v1/identity.go, api/ocm/tools/signing/digest.go
As proposed and discussed a simpler version of `VerifyResourceDigest`.
The new name is a bit misleading and probably the name of the old function should be adjusted.
@mandelsoft What do you think? And can you please explain the behaviour of the `VerifiedStore`?
=> Add a simpler digest verify function

api/oci/ref.go, api/oci/utils.go, api/ocm/cpi/repocpi/bridge_cv.go, api/ocm/extensions/accessmethods/maven/README.md, api/ocm/extensions/accessmethods/ociartifact/method.go, api/ocm/extensions/accessmethods/ociartifact/method_test.go, api/ocm/extensions/accessmethods/relativeociref/transfer_test.go, api/ocm/extensions/blobhandler/handlers/generic/ocirepo/blobhandler.go, api/ocm/extensions/blobhandler/handlers/generic/ocirepo/upload_test.go, api/ocm/extensions/blobhandler/handlers/oci/ocirepo/blobhandler.go, api/ocm/extensions/blobhandler/handlers/oci/ocirepo/handler_test.go, api/ocm/extensions/download/handlers/ocirepo/handler.go, api/ocm/extensions/repositories/genericocireg/repo_test.go, cmds/ocm/commands/ocicmds/tags/show/cmd.go, cmds/ocm/commands/ocmcmds/components/transfer/disableupload_test.go, cmds/ocm/commands/ocmcmds/components/transfer/upload_test.go
If in a OCI ref both, the tag and the digest is given, the tag is preferred, so far. BUt the digest should always have precedence.
Fixes #911
=> OCI: prefer digest over tag

api/ocm/internal/modopts.go, api/ocm/tools/signing/handle.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/interface.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/utils.go, cmds/ocm/commands/ocmcmds/common/cmds/signing/cmd.go, cmds/ocm/commands/ocmcmds/common/resources.go, cmds/ocm/commands/ocmcmds/components/hash/cmd.go, cmds/ocm/commands/ocmcmds/components/hash/cmd_test.go, cmds/ocm/common/processing/processing.go
In recursive mode of `ocm hash components`, the closure calculation is done in the processing chain after
the mapping to the hash object. This cause type assertion panics.
Additionally, the recalculating hashes for a component version using a shared state, also a panic occurs, because it has
already been calculated as part of a closure.
Both problems are fixed with this PR.
Then, it adds some more flexibility to the input handling, enabling the use of the constructor processing in 
a more flexible way for other programs besides the usual cli commands.
=> CLI:  fix recursive mode for ocm hash component

api/cli/internal/context.go, api/utils/template/gotmpl.go, api/utils/template/none.go, api/utils/template/registry.go, api/utils/template/spiff.go, api/utils/template/subst.go, api/utils/template/template.go, cmds/ocm/app/app.go, cmds/ocm/commands/ocmcmds/names/names.go, go.mod, go.sum
- Support standard object types for command plugins 
The CLI supports verbs on objects (e.g, get component). For such object names aliases are used 
(e.g. for componentversions, it is possible to use component or cv, instead)
A CLI command provided by a plugin may use such a standard object name. The new integration takes the aliases provided
by the CLI into account.
- Options for templater types
Templaters are used by the CLI to process the constructor files, but possible also by direct lib users.
So far, templaters are created for a value set, but without other arbitrary type specific optional parameters.
The templater configuration now offers settings passed to the templater constructor. This is used by spiff
to enable or restrict the OS mode. By default, file system access is …
=> Support standard object types for command plugins + options for templater types

api/ocm/extensions/blobhandler/config/type.go, docs/reference/ocm_configfile.md
Just doing the documentation fix, without any renaning. NOTHING more!
This is now a replacement of: https://github.com/open-component-model/ocm/pull/944
renaming might happen with implementation of:
https://github.com/open-component-model/ocm-project/issues/286
=> documentation: fix uploader documentation

api/oci/extensions/repositories/artifactset/artifactset.go, api/oci/extensions/repositories/ctf/repository.go, api/ocm/cpi/repocpi/backend.go, api/ocm/cpi/repocpi/bridge_cv.go, api/ocm/extensions/repositories/comparch/componentarchive.go, api/ocm/extensions/repositories/comparch/repository.go, api/ocm/extensions/repositories/composition/repository.go, api/ocm/extensions/repositories/genericocireg/componentversion.go, api/ocm/extensions/repositories/virtual/access.go, api/ocm/extensions/repositories/virtual/componentversion.go, api/ocm/extensions/repositories/virtual/example/example.go, api/utils/accessobj/accessobject.go, api/utils/accessobj/accessstate.go, api/utils/accessobj/filesystemaccess.go, api/utils/accessobj/format-tar.go
Extend the CV implementation API to provide information, whether an Update of the descriptor has been done.
This information is then used to trigger the pubsub handler.
If no update has been done, the query of the repository's pubsub info is omitted.
=> Introduce update state on CV implementation API

.github/workflows/release.yaml, RELEASE_PROCESS.md
partially resolves #997 by being able to default to candidates, releaes branches and adding a small documentation paragraph
=> chore(ci): make sure we use candidates and branches by default

.github/workflows/stale.yaml
Changes the stale configuration to https://github.com/open-component-model/.github/blob/main/.github/workflows/stale.yml
=> chore(ci): use reusable stale bot configuration

go.mod
see #293 for context, causing us to redact 0.16
Redacts version 0.16 in its entirety on the next release as we do not want consume ORAS as is
=> fix!(release): retract 0.16.0-z

.github/workflows/release.yaml
This allows us to also generate the README.md files automatically so that they contain correct references
#990
=> chore(release): also call make generate to update files

.github/workflows/release.yaml, examples/lib/tour/01-getting-started/README.md
runs make generate because it was only run on the release branch. adds check as mandatory dep of release to make sure the tag-check inside is not rgiacing against release. adds necessary build steps for tools needed in make generate.
=> chore: release fallout corrections

.github/workflows/publish-to-other-than-github.yaml
push to Chocolatey fails as long as we don't set `RELEASE_VERSION` environment correctly
=> chore: set RELEASE_VERSION correct

.github/workflows/release-drafter.yaml
Disables the go cache for the release note drafter to avoid pulling in 4gi of cached data onto our instances (so we avoid no space left on device issues)
=> chore: disable runner cache for release note drafter

cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/components.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/elements.go, cmds/ocm/commands/ocmcmds/components/add/cmd_test.go, cmds/ocm/commands/ocmcmds/components/add/testdata/component-constructor-old.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/component-constructor.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/component-dup-ref.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/component-dup-res.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/components-dup.yaml, cmds/ocm/commands/ocmcmds/components/add/testdata/components.yaml, components/helmdemo/component-constructor.yaml, components/subchartsdemo/component-constructor.yaml
The component constructor used the field `componentReferences` from the v2 version of the component descriptor.
in v3 this has been corrected to `references` (it described component version references and no component references).
This should reflected in the constructor files, also.
the old field is now deprecated (but still works). Instead, the field `references` is supported, now.
It is not possible to use both fields at the same time.
Fixes https://github.com/open-component-model/ocm/issues/1041
=> component constructor with references field

api/credentials/internal/identity.go, api/credentials/internal/identity_test.go
Fix empty identity value regression.
The regression was introduced after this [PR](https://github.com/open-component-model/ocm/pull/927) adding a custom unmarshaler for consumer identities which allows to specify values other than string (e.g. port: 5000), even though consumer identity is a map[string]string.
=> bug: fix unmarshal consumer identity with empty value

api/ocm/extensions/accessmethods/ociartifact/method.go
Although we allow to fetch components from an `http` registry by specifying the scheme, we unintentionally didn't enable fetching artifacts specified in an oci access from an http registries due to this bug.
=> bug: allow http protocol for oci access

cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/options.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go, cmds/ocm/commands/ocmcmds/components/add/cmd.go, cmds/ocm/commands/ocmcmds/components/add/cmd_test.go, cmds/ocm/commands/ocmcmds/components/add/testdata/component-constructor-skip.yaml, docs/reference/ocm_add_componentversions.md
This PR adds the option `--skip-digest-generation` to the `ocm add components` command.
It generally disables the digest generation for all added resources.
Additionally, the resource description may set `skipDigestGeneration` to `true` to disable the digest 
generation  for this particular resource.
Fixes https://github.com/open-component-model/ocm-project/issues/322
=> skip digest for component constructors

cmds/ocm/commands/ocmcmds/common/addhdlrs/base.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/elements.go, cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go, cmds/ocm/commands/ocmcmds/components/add/cmd.go, docs/reference/ocm_add_componentversions.md
complete #1070
Move handler-local options correctly to the comp handler and adapt the
using code to reflect this change.
=> fix: add back scheme option after it was accidentally removed

.github/workflows/blackduck_scan_scheduled.yaml
Accidentally the go env didnt get set for blackduck which caused the cron job to fail before. This now sets it correctly
fix #1074
=> fix: fixup blackduck scan job

api/oci/ociutils/ref.go, api/oci/ociutils/ref_test.go, api/oci/ociutils/suite_test.go, api/oci/ref.go, api/oci/testhelper/manifests.go, api/ocm/extensions/accessmethods/relativeociref/method_test.go
PR #1033 introduced a split of the OCI version info from the repository part.
The method `Version` checks the inverted condition for an existing version inf.
=> fix version info for OCI refs

api/oci/ociutils/ref.go, api/oci/ociutils/ref_test.go, api/oci/ociutils/suite_test.go, api/oci/ref.go, api/oci/testhelper/manifests.go, api/ocm/extensions/accessmethods/relativeociref/method_test.go, docs/releasenotes/v0.18.0-rc.2.md, examples/lib/tour/01-getting-started/README.md
Cherry Pick from https://github.com/open-component-model/ocm/commit/a1890c261fc2a5ffb58ee1590662b04a752fa9a0
=> [release-v0.18.0] fix: version info for OCI refs

examples/lib/tour/01-getting-started/README.md, examples/lib/tour/01-getting-started/example.go, examples/lib/tour/07-resource-management/README.md, examples/lib/tour/07-resource-management/example.go
Pins the tour versions for the guide so that we dont have to regenerate them on every successful release...
=> chore: pin version in tour guide to avoid regeneration

.github/config/goreleaser.yaml
Currently all releases (even if candidates) were published as the latest release even though they should be marked as prereleases. This changes this by using the correct goreleaser indicator:
```
```
=> fix: correctly set prerelease flag

.github/release-drafter.yml
makes sure that we can use the `breaking-change` label to correctly mark changes that can lead to regressions if not taken care of.
=> chore: add breaking change release label

cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go, cmds/ocm/commands/ocmcmds/components/add/testdata/component-constructor-skip.yaml
This is a follow up from https://github.com/open-component-model/ocm/pull/1070 as @fabianburth and I decided that it would probably be best to group process related options under a specific struct to make it more explicit that they are optional and not part of the normal resource description
=> chore: move process options to struct

.github/config/labeler.yml, .github/workflows/pull-request.yaml
currently the github actions label is not set automatically and I tend to forget it. Thats why this PR is changing this so that the labeller config also sets the github actions label if anything in `.github` changes
=> chore: automatically set github actions label

.github/config/labeler.yml
this fixes up the labeler job config that I messed up in 1fb2f09fcfaaa0bfab9f54678bac414bcb0a8821
=> chore: fixup labeler job config

.github/workflows/components.yaml, .github/workflows/release.yaml, components/demoplugin/Makefile, components/ecrplugin/Makefile, components/helmdemo/Makefile, components/helminstaller/Makefile, components/ocmcli/Makefile, components/subchartsdemo/Makefile
Makes sure that release notes are correctly drawn in and that we always have the version set correctly in our CTFs.
This fixes up the release action in 2 important ways:
1. As part of the removal of the release notes we now no longer have a file to use for release notes to give to goreleaser. This means we have to temporarily create one
2. While discovering this I noticed that the Component Versions that are built, are actually using the `VERSION` variable while `EFFECTIVE_VERSION` is a combination of VERSION+COMMIT by default. I didnt want to change this behavior originally, so now I started to use VERSION for the Makefiles (which also means I had to export them as settable). This now leads to correct CTF versions `v0.19.0-rc.1` instead of `v0.19.0-dev` for example.
As such its a follow …
=> chore: fixup release action versioning and notes process

.github/config/markdown-link-check.json, .github/config/markdownignore, .github/config/wordlist.txt, .github/workflows/release-drafter.yaml, hack/collapse/.gitignore, hack/collapse/auto_collapse.sh, hack/collapse/test_auto_collapse.sh, hack/collapse/test_example.md, hack/collapse/test_example_expected_collapsible.md
Adds a small script that autocollapses our release notes again because we no longer use release drafter
Backported to allow the release notes to be drafted correctly.
=> chore(backport): autocollapse release notes (#1145)

.github/workflows/release-drafter.yaml, hack/collapse/auto_collapse.sh
the release notes that were fixed up require a small adjustment to be able to deal with properly multilined files.
This is because the notes are stored in bash variables which removes newlines by default. Now they are properly formatted in again and we also fixup the script so that the line count is correct
Makes sure that multilined release notes are interpreted correctly and dont break out. This happened with release/v0.19 so that commit was patched up by force push to test out the notes
=> chore: fixup release notes

.github/settings.yml
1. merge https://github.com/open-component-model/ocm/pull/1115
2. execute [migrate-labels.sh](https://github.com/open-component-model/.github/blob/main/labels/migrate-labels.sh) on `ocm`
3. merge this PR
=> chore: inherit from .github labels

.github/config/release.yml
this makes it so that issues listing a dependency kind will be sorted into the correct category instead of maintenance even though they are listed as chore(deps)
=> chore: prioritize deps over chore

.github/config/release.yml
this adds a catch all category if none of the labels mentioned in the config didnt apply.
=> chore: add catch all category for release

.github/dependabot.yml, Dockerfile, components/ocmcli/Dockerfile
This simplifies the docker images update process because it runs through dependabot.yml
=> chore: make sure that dockerfiles are setup in a standard way

.github/workflows/pull-request.yaml
Uses any_of as per https://github.com/agilepathway/label-checker?tab=readme-ov-file#checks because its technically possible that a PR fits multiple kinds (e.g. chore + dependency)
=> chore: changes label check to any_of

api/utils/template/merge.go, go.mod
`In [1.0.0](https://github.com/imdario/mergo/releases/tag/1.0.0) Mergo moves to a vanity URL dario.cat/mergo. No more v1 versions will be released.`
see https://github.com/darccio/mergo?tab=readme-ov-file#100
=> chore(deps): use mergo vanity url

.github/workflows/components.yaml
temporarily disables the docker build cache because of token pass issues (while I locally didnt face any issues the docker login action doesnt seem to propagate correctly to the push)
This is to unblock main builds from failing, further investigation necessary
=> fix: allow cache push through PAT

cmds/ocm/commands/ocmcmds/common/options/overwriteoption/option.go
Fixes a bug in the `ocm transfer` command, that caused the `--enforce` option to be ignored if `--overwrite` was set. 
#1186
=> fix: ocm transfer ignored --enforce when --overwrite is set

api/utils/cobrautils/template.go, cmds/cliplugin/cmds/cmd_test.go, cmds/subcmdplugin/cmds/cmd_test.go
Renames the `Flags` section in `--help` to `Options`. The `Synopsis` currently shows `ocm [<options>] ...`, with <options> referring to the command line options listed under `Flags`. This might confuse users (or at least concern if something does not work). 
**Before:**
```
> ocm get component --help
ocm get componentversions — Get Component Version
Synopsis:
ocm get componentversions [<options>] {<component-reference>}
Aliases:
componentversions, componentversion, cv, components, component, comps, comp, c
Flags:
-c, --constraints constraints   version constraint
-h, --help                      help for componentversions
--latest                    restrict component versions to latest
--lookup stringArray        repository name or spec for closure lookup fallback
-o, --output string …
```
=> docs: adjust flags to options in cobra help and usage template

.github/workflows/publish-to-other-than-github.yaml
last publish release didn't work: https://github.com/open-component-model/ocm/actions/runs/12349057328/job/34459090022
=> chore(github_action): add generate_token to push-to-website

cmds/ocm/topics/toi/bootstrapping/topic.go, docs/reference/ocm_toi-bootstrapping.md
The command doc for ocm toi-bootstrapping shows the wrong type for the reference to a TOI executor.
Fixes [#339](https://github.com/open-component-model/ocm-project/issues/339)
=> fix: fix toi doc

.github/workflows/integration-test.yaml
This will use the Pull Request Branch Reference and Repository to checkout OCM
=> chore: use the pull request head to run the integration tests

api/ocm/tools/toi/drivers/docker/driver.go
Related to https://github.com/open-component-model/ocm-project/issues/359
=> fix: do not handle root folder and the . folder

.github/config/golangci.yaml, .github/config/wordlist.txt, api/ocm/compdesc/norm_test.go, api/ocm/compdesc/normalization.go, api/ocm/compdesc/normalizations/init.go, api/ocm/compdesc/normalizations/jsonv1/norm.go, api/ocm/compdesc/normalizations/jsonv2/norm.go, api/ocm/compdesc/normalizations/jsonv3/norm.go, api/ocm/compdesc/normalizations/legacy/legacy.go, api/ocm/selectors/accessors/accessors.go, cmds/ocm/commands/ocmcmds/common/options/hashoption/option.go, cmds/ocm/commands/ocmcmds/common/options/signoption/option.go, cmds/ocm/commands/ocmcmds/components/hash/cmd_test.go, cmds/ocm/commands/ocmcmds/components/sign/cmd_test.go, docs/reference/ocm_hash_componentversions.md, docs/reference/ocm_logging.md, docs/reference/ocm_sign_componentversions.md
Note that this introduces a json normalization algorithm v3 which technically will break a minor release. however this is needed as we currently broke hashing and need to offer a working alternative. thus it should have been part of v0.19.0 already: https://github.com/open-component-model/ocm/issues/1214
Package jsonv3 provides a normalization which is completely based on the abstract (internal) version of the component descriptor and is therefore agnostic of the final serialization format. Signatures using this algorithm can be transferred among different schema versions, as long as is able to handle the complete information using for the normalization. jsonv2 is the predecessor of this version but had internal defaulting logic that is no longer included as part of this normalization. …
=> feat(normalisation): jsonNormalisation/v3 and fixes to jsonNormalisation/v1 as well as jsonNormalisation/v2 (#1218)

api/credentials/extensions/repositories/memory/config/type.go, docs/reference/ocm_configfile.md
Although the text: `specialsecret2` might not be used as real password, let's try to use always a more obvious placeholder: `<my-secret-password>`
fixes: https://github.com/open-component-model/ocm/security/secret-scanning/6
=> chore: Copilot Secret Scanning, let's use always the same sample

.github/workflows/release.yaml
Only passes the body of the release notes and encodes it properly before passing so that we can not run into issues when handling the notes in different steps as an output
https://github.com/open-component-model/ocm/actions/runs/12690118935/job/35370314340#step:13:2 failed
fix https://github.com/open-component-model/ocm-project/issues/363
=> chore(ci): ensure body is encoded correctly and can never be recognized as secret for release

.github/workflows/release.yaml
Only passes the body of the release notes and encodes it properly before passing so that we can not run into issues when handling the notes in different steps as an output
https://github.com/open-component-model/ocm/actions/runs/12690118935/job/35370314340#step:13:2 failed
fix https://github.com/open-component-model/ocm-project/issues/363
=> chore(ci): ensure body is encoded correctly and can never be recognized as secret for release (#1238)

.github/workflows/release.yaml
This is a final correction to the release notes writer that makes sure the newlines are kept without using base64 but still maintaining that only the body is forwarded to avoid secret leaks
fix https://github.com/open-component-model/ocm-project/issues/363
already fixed in releases/v0.19 as I used this branch to test this fix.
=> chore(ci): patch release note write

.github/config/golangci.yaml, api/ocm/compdesc/meta/v1/signature.go, api/ocm/compdesc/normalizations/jsonv1/norm.go, api/ocm/compdesc/normalizations/jsonv2/norm.go, api/ocm/compdesc/normalizations/legacy/legacy.go, api/ocm/tools/signing/digestctx.go
This make sure that the (very convoluted) signing implementation normalizes with the legacy patch we applied during the normalization of the descriptor to avoid mismatches in resource identities during digest propagation.
fix https://github.com/open-component-model/ocm/issues/1245
=> fix(workaround): allow old norm algos to be hashed with old digest ctxts

api/credentials/internal/consumers.go, api/utils/logging/roundtripper.go, api/utils/logging/roundtripper_test.go
=> chore: resolve security findings

RELEASE_PROCESS.md
Actually, it's NOT possible to remove the suffix in the text box, since it's mandatory to not be empty.
But when the RC-checkbox isn't checked, it won't be taken into account.
=> chore(docs): Update RELEASE_PROCESS.md

Dockerfile
raise Alpine version für OCM CLI Image
=> chore: raise alpine version

api/ocm/extensions/accessmethods/git/method.go, api/tech/git/identity/identity.go, cmds/ocm/commands/ocmcmds/common/inputs/types/git/spec.go, go.mod, go.sum
this is in relation to CVE-2023-46402
(cherry picked from commit e2e61ff20bbb22cff6a23e2d87f82ca6c22b89ae)
=> fix: cap max length of git repository urls (#1298)

.github/workflows/blackduck_scan_scheduled.yaml
remove .bridge folder from scanning to avoid false positives
=> chore: remove .bridge folder from scans

.github/workflows/flake_vendorhash.yaml, flake.nix
With the upgrade of go v1.24 the nix flake update action didn't work anymore
import builtins fetchGit with rev latest commit sha from
https://github.com/NixOS/nixpkgs/commits/nixos-unstable/
73cf49b8ad837ade2de76f87eb53fc85ed5d4680
fixes broken GHA https://github.com/open-component-model/ocm/actions/workflows/flake_vendorhash.yaml
=> chore(nixos): fix broken nix-flake-hash update

flake.lock, flake.nix
bump flake.lock to nixpkgs-unstable
clean up flake.nix
- remove the gitfetch nixpkgs workaround
- fix the evaluation warning: "buildGoModule: specify CGO_ENABLED with env.CGO_ENABLED instead"
=> chore: bump flake.lock to nixpkgs-unstable and clean up flake.nix

api/oci/extensions/repositories/ocireg/namespace.go
Makes sure resolution of artifacts resolves as Unknown Error for OCM if its something like a 400
fix https://github.com/open-component-model/ocm/issues/1362
=> fix: make sure that other resolve requests such as 400 are also returned as unknown errors so that OCM recognizes them

.github/workflows/lint_and_test.yaml
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
to exclude changes to workflow files the ignore-paths needed to be fixed.
=> chore: update paths-ignore in lint_and_test workflow to be more specific

.github/workflows/lint_and_test.yaml
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
remove ignore-paths due to conflict with required check
=> chore: remove paths-ignore from lint_and_test workflow for pull requests and pushes

.github/workflows/lint_and_test.yaml, .github/workflows/release.yaml
Fix for release workflow.
https://github.com/open-component-model/ocm/actions/runs/14058967852
```console
[Invalid workflow file: .github/workflows/release.yaml#L274](https://github.com/open-component-model/ocm/actions/runs/14058967852/workflow)
The workflow is not valid. .github/workflows/release.yaml (Line: 274, Col: 11): Secret BDBA_USERNAME is required, but not provided while calling. .github/workflows/release.yaml (Line: 274, Col: 11): Secret BDBA_PASSWORD is required, but not provided while calling.
```
=> fix: inherit secret for Trigger BDBA Scan

RELEASE_PROCESS.md
As discussed in Slack, we want to make release schedule more strict. New releases should be produced on the first day of new sprint.
=> docs: release on first day of the sprint

go.mod
Backport the fix of #1399
retract v0.22.0 due to accidental release
=> fix: retract v0.22.0 in releases/v0.23

hack/Makefile
@mandelsoft created a new tag: https://github.com/mandelsoft/mdref/releases/tag/v0.5.1 which doesn't result in sha-sum mismatches.
We should not use the ugly workaround with the `GONOSUMDB` setting.
fixes: https://github.com/mandelsoft/mdref/issues/1
=> chore: pin `mdref` to v0.5.1

flake.lock, flake.nix
Fixes the flake dependency on go_1_24.
Switch back to stable nixpkgs and `nix flake update`.
=> chore: switch to stable 24.11

.github/workflows/flake_vendorhash.yaml
From time to time, we should make sure to also update the flake we're using to create our own.
When switching to the latest patch version of go, sometimes the action fails:
https://github.com/open-component-model/ocm/actions/runs/14731906561
So we need to ensure, the file: https://github.com/open-component-model/ocm/blob/main/flake.lock get's updated as well. Which is done by: `nix flake update`
=> chore: run `nix flake update`

api/ocm/elements/artifactaccess/githubaccess/resource.go, api/ocm/extensions/accessmethods/github/README.md, api/ocm/extensions/accessmethods/github/cli.go, api/ocm/extensions/accessmethods/github/method.go, api/ocm/extensions/accessmethods/github/method_test.go, docs/reference/ocm_add_resource-configuration.md, docs/reference/ocm_add_resources.md, docs/reference/ocm_add_source-configuration.md, docs/reference/ocm_add_sources.md, docs/reference/ocm_ocm-accessmethods.md
This reverts commit 43632aa3.
We have too many users reporting issues with the ref+commit combination as this was not spec compliant. We need to revert this change asap to stop breaking existing component version flows
=> fix(revert): make sure that ref is an option in the gitHub AccessMethod (#1406)

api/ocm/elements/artifactaccess/githubaccess/resource.go, api/ocm/extensions/accessmethods/github/README.md, api/ocm/extensions/accessmethods/github/cli.go, api/ocm/extensions/accessmethods/github/method.go, api/ocm/extensions/accessmethods/github/method_test.go, docs/reference/ocm_add_resource-configuration.md, docs/reference/ocm_add_resources.md, docs/reference/ocm_add_source-configuration.md, docs/reference/ocm_add_sources.md, docs/reference/ocm_ocm-accessmethods.md
This reverts commit 43632aa3.
We have too many users reporting issues with the ref+commit combination as this was not spec compliant. We need to revert this change asap to stop breaking existing component version flows
(cherry picked from commit 340d282f6fee1d7dd90cba4bb3b7908acbef25a8)
=> fix(revert): make sure that ref is an option in the gitHub AccessMethod (#1406) (#1460)

api/ocm/extensions/download/handlers/helm/download_test.go, api/ocm/extensions/download/handlers/helm/handler.go, api/ocm/extensions/download/handlers/helm/handler_test.go
in the helm downloader, there was a case when the chart data was overwritten with the provenance data. if the target path passed to the downloader was a path such as `path.tgz` then this path was reused for writing the provenance file.
This was now fixed and there will be:
1. A download path pointing to the .tgz => chart.tgz
2. A provenance file (if it exists) => chart.prov
Note that before, due to buggy behavior the output provenance file was just called `chart` because the .prov file extension was not properly added. this has been fixed as well.
additionally if the file path was `tar.gz` instead of `tgz`, the file ending removal was incorrect. this has been fixed.
This was also the last reason why the ocm download resource command returned incorrect data in the tgz when downloading a …
=> fix: make sure that helm downloader does not overwrite chart with provenance data

api/ocm/extensions/download/handlers/helm/download_test.go, api/ocm/extensions/download/handlers/helm/handler.go, api/ocm/extensions/download/handlers/helm/handler_test.go
in the helm downloader, there was a case when the chart data was overwritten with the provenance data. if the target path passed to the downloader was a path such as `path.tgz` then this path was reused for writing the provenance file.
This was now fixed and there will be:
1. A download path pointing to the .tgz => chart.tgz
2. A provenance file (if it exists) => chart.prov
Note that before, due to buggy behavior the output provenance file was just called `chart` because the .prov file extension was not properly added. this has been fixed as well.
additionally if the file path was `tar.gz` instead of `tgz`, the file ending removal was incorrect. this has been fixed.
This was also the last reason why the ocm download resource command returned incorrect data in the tgz when downloading a …
=> fix: make sure that helm downloader does not overwrite chart with provenance data (#1481)

.github/workflows/integration-test.yaml
Adds a ternary expression as per
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example
so that we dont have a "skipped" integration test job in our job list that might cause confusion
=> chore: use ternary operator to avoid "skipped" integration test job

api/ocm/extensions/download/handlers/helm/download_test.go, api/ocm/extensions/download/handlers/helm/handler.go, api/ocm/extensions/download/handlers/helm/handler_test.go
According to the helm
[spec](https://github.com/helm/community/blob/05eab5bba990d4f5556f90bfc001662d1a76f9a5/hips/hip-0006.md#2-support-for-provenance-files)
> assuming the presence of a file suffixed with .prov sitting next to a
chart .tgz in a repository.
This is why, we initially downloaded the provenance file into a file with only the `.prov` extension. However, according to the [helm documentation](https://github.com/helm/helm-www/blob/cf3e4f875101fa3f72ff6194499b5365723f0ec1/content/en/docs/topics/provenance.md)
> For example, if the base URL for a package is
https://example.com/charts/mychart-1.2.3.tgz, the provenance file, if it exists, MUST be accessible at
https://example.com/charts/mychart-1.2.3.tgz.prov.
Accordingly, we changed the filename for the provenance content to …
=> fix: correct filename for provenance file (#1492)

api/ocm/extensions/download/handlers/helm/download_test.go, api/ocm/extensions/download/handlers/helm/handler.go, api/ocm/extensions/download/handlers/helm/handler_test.go
According to the helm
[spec](https://github.com/helm/community/blob/05eab5bba990d4f5556f90bfc001662d1a76f9a5/hips/hip-0006.md#2-support-for-provenance-files)
> assuming the presence of a file suffixed with .prov sitting next to a
chart .tgz in a repository.
This is why, we initially downloaded the provenance file into a file with only the `.prov` extension. However, according to the [helm documentation](https://github.com/helm/helm-www/blob/cf3e4f875101fa3f72ff6194499b5365723f0ec1/content/en/docs/topics/provenance.md)
> For example, if the base URL for a package is
https://example.com/charts/mychart-1.2.3.tgz, the provenance file, if it exists, MUST be accessible at
https://example.com/charts/mychart-1.2.3.tgz.prov.
Accordingly, we changed the filename for the provenance content to …
=> chore: fix correct filename for provenance file (#1492)

go.mod, go.sum
```
➜ ./bin/ocm install pllug
ocm install — Install New Ocm Cli Components
Synopsis:
ocm install [<options>] <sub-command> ...
Available Commands:
plugins     install or update an OCM plugin
Options:
-h, --help   help for install
Description:
Install new OCM CLI components
Use ocm install <command> -h for additional help.
ocm on  remove-cobra-fork [$] via :hamster: v1.24.2
➜ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
ocm on  main [$] via :hamster: v1.24.2
➜ go build -o bin/ocm cmds/ocm/main.go
ocm on  main [$] via :hamster: v1.24.2 took 20s
➜ ./bin/ocm install pllug
Error: unknown command "pllug" for "ocm install"
Run 'ocm install --help' for usage.
ocm on  main [$] via :hamster: v1.24.2
```
=> chore!: migrate to native cobra library

api/ocm/extensions/accessmethods/github/method.go
The field part of this access type as per specification. Although, we won't leverage it for now in the implementation, we add it to the spec, so it can at least be read.
@zkdev
=> feat: add ref to github access spec

.github/workflows/flake_vendorhash.yaml
Bumps our nix installer package in an attempt to get a later go version for our flake bumps
=> chore: update Nix installer package to version 2.31.0 in flake_vendorhash workflow

.github/workflows/release.yaml
https://github.com/actions/download-artifact/releases/tag/v5.0.0 has a breaking change that causes the path to now be without a subpath named after the artifact. that means we need to patch the artifact source path
After cherry pick this will fix our currently failing RC release
=> fix(ci): correct artifact download path in release workflow to ensure proper recognition

api/ocm/tools/transfer/transferhandler/spiff/handler.go, api/ocm/tools/transfer/transferhandler/spiff/handler_test.go, cmds/ocm/commands/ocmcmds/components/transfer/cmd.go
- Make `ocm transfer {cv|ctf}` respect `--omit-access-types` (as originally intended).
- Unwrap the standard transfer handler so omit logic is applied consistently across handlers.
- Fix spiff handler so it no longer reinstates access types when omit is requested. 
Previously, users might have used the flag `--omit-access-types` with a transfer and would have changed behavior now (flag was ignored). 
After this change, `--omit-access-types` takes effect for any transfer as originally intended. 
**Users expecting resources to be transferred even though they were mentioned with their access type in  `--omit-access-types` must likely drop `--omit-access-types` for that access type if they used it before and expected the resources to still be present.**
Fixes #1500
=> fix!: unwrap standard transfer handler and fix spiff handler

api/ocm/tools/transfer/transferhandler/spiff/handler.go, api/ocm/tools/transfer/transferhandler/spiff/handler_test.go, cmds/ocm/commands/ocmcmds/components/transfer/cmd.go
- Make `ocm transfer {cv|ctf}` respect `--omit-access-types` (as originally intended).
- Unwrap the standard transfer handler so omit logic is applied consistently across handlers.
- Fix spiff handler so it no longer reinstates access types when omit is requested.
Previously, users might have used the flag `--omit-access-types` with a transfer and would have changed behavior now (flag was ignored).
After this change, `--omit-access-types` takes effect for any transfer as originally intended.
**Users expecting resources to be transferred even though they were mentioned with their access type in `--omit-access-types` must likely drop `--omit-access-types` for that access type if they used it before and expected the resources to still be present.**
Fixes #1500
---------
(cherry picked from …
=> fix!: unwrap standard transfer handler and fix spiff handler (#1501)

Dockerfile
Bumps distroless/static-debian12 from `a9f88e0` to `e8a4044`.
---
updated-dependencies:
- dependency-name: distroless/static-debian12 dependency-version: nonroot dependency-type: direct:production ...
Supersedes #1619 as it contained non-signed commits.
=> chore(deps): bump distroless/static-debian12 from `a9f88e0` to `e8a4044`
